"""DNA-binding domain annotation, and the admission policy for what may enter the dataset.

**`dbd_seq` is the Pfam envelope padded by `domain.padding_aa` residues on each side, not
the bare envelope.** See `configs/thresholds.yaml` and `docs/DOMAIN_POLICY.md` for why.

A construct is admitted only if the stored subunit satisfies all three conditions:

1. **Sole responsibility** — it alone produced the measured interaction. A construct whose
   Pfam hits span two families (PAX+homeodomain, POU+homeodomain) fails: two domains bind,
   and nothing in the data says which produced a given 8-mer's score.
2. **One continuous region** — not fragments scattered through the protein. A C2H2 array is
   2-6 separate ~23-residue folds on flexible linkers, each needing its own Zn(2+), so it
   fails even though every finger belongs to one family.
3. **The variation lies inside it** — a mutation outside the stored region makes a variant
   sequence-identical to its wild type while carrying a different label. Padding exists to
   satisfy this condition, and `audit_variant_positions` checks it directly.

Rejections are reported, never silently repaired.

**Scanning uses the full Pfam-A library, not a hand-picked subset.** An earlier version
carried HMMs only for the nine families present in the first four sources, which meant
constructs from other families were rejected as `no_domain` because the HMM was missing
rather than because nothing was there. UniPROBE spans 86 distinct domain labels.

Because a full-Pfam scan also finds domains that have nothing to do with DNA, the admission
policy is evaluated over **DNA-binding families only** (`dbd_families.txt`). A DBD sitting
beside an unrelated domain still satisfies condition 1 — that DBD is solely responsible for
the DNA interaction — so non-DBD hits are recorded on the call and otherwise ignored.
"""

from __future__ import annotations

import functools
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pyhmmer
from pyhmmer.easel import Alphabet, TextSequence

from snp2prot import thresholds
from snp2prot.config import PROJECT_ROOT


class Rejection(str):
    """Why a construct was not admitted. A plain string so it lands in reports unchanged."""


MIXED_FAMILIES = Rejection("mixed_families")
REPEAT_ARRAY = Rejection("repeat_array")
NO_DOMAIN = Rejection("no_domain")


@dataclass(frozen=True)
class DomainHit:
    family: str
    start: int  # 1-based, inclusive, in the scanned sequence
    end: int


@dataclass(frozen=True)
class DomainCall:
    """The admission decision for one construct."""

    sequence: str | None  # the padded domain, or None if rejected
    family: str
    start: int
    end: int
    hits: tuple[DomainHit, ...]
    rejection: Rejection | None = None
    #: Non-DNA-binding Pfam hits found in the same construct. Recorded, not acted on.
    other: tuple[DomainHit, ...] = ()

    @property
    def ok(self) -> bool:
        return self.rejection is None


def _name(x: Any) -> str:
    return x.decode() if isinstance(x, bytes) else str(x)


@functools.lru_cache(maxsize=1)
def dbd_families(path: str | None = None) -> frozenset[str]:
    """Pfam family names that are DNA-binding domains.

    Generated by `scripts/build_dbd_family_list.py` from the domain labels UniPROBE itself
    publishes, resolved against Pfam-A's own NAME fields. Only these families are considered
    when applying the admission policy.
    """
    cfg = thresholds.load()["domain"]
    f = Path(path or cfg["dbd_families"])
    if not f.is_absolute():
        f = PROJECT_ROOT / f
    if not f.exists():
        raise FileNotFoundError(f"DBD family list not found: {f}")
    return frozenset(
        line.split("#")[0].strip()
        for line in f.read_text().splitlines()
        if line.strip() and not line.startswith("#")
    )


def _hmm_path() -> Path:
    cfg = thresholds.load()["domain"]
    p = Path(cfg["hmm_db"])
    if not p.is_absolute():
        p = PROJECT_ROOT / p
    if not p.exists():
        raise FileNotFoundError(f"Pfam HMM library not found: {p}")
    return p


def scan(
    sequences: dict[str, str], hmm_path: str | Path | None = None, cpus: int = 0
) -> dict[str, list[DomainHit]]:
    """Pfam-scan many sequences against the full library, using each family's own threshold.

    Returns every hit, DNA-binding or not; `call_domain` decides which ones the policy sees.
    """
    abc = Alphabet.amino()
    keys = list(sequences)
    queries = [TextSequence(name=k.encode(), sequence=sequences[k]).digitize(abc) for k in keys]
    found: dict[str, list[DomainHit]] = {k: [] for k in keys}
    path = Path(hmm_path) if hmm_path else _hmm_path()
    with pyhmmer.plan7.HMMFile(path) as hmms:
        for top in pyhmmer.hmmer.hmmscan(queries, hmms, bit_cutoffs="gathering", cpus=cpus):
            name = _name(top.query.name)
            for hit in top:
                for dom in hit.domains.included:
                    # In hmmscan the roles are swapped relative to a per-family search, but
                    # pyhmmer still reports target_from/to in sequence coordinates. Verified
                    # against ARX, which gives Homeodomain[15-71] either way.
                    found[name].append(
                        DomainHit(
                            _name(hit.name), dom.alignment.target_from, dom.alignment.target_to
                        )
                    )
    return {k: sorted(v, key=lambda h: h.start) for k, v in found.items()}


def call_domain(
    sequence: str, hits: list[DomainHit], config: dict[str, Any] | None = None
) -> DomainCall:
    """Apply the admission policy to one construct and return the padded domain."""
    cfg = config or thresholds.load()["domain"]
    pad = int(cfg["padding_aa"])

    # Only DNA-binding families take part in the policy. A construct carrying a homeodomain
    # plus, say, a LIM or PWWP domain is still attributable: the homeodomain is what binds.
    known = dbd_families()
    other = tuple(h for h in hits if h.family not in known)
    hits = [h for h in hits if h.family in known]
    families = {h.family for h in hits}

    if not hits:
        if not cfg.get("allow_no_domain", False):
            return DomainCall(None, "", 0, 0, (), NO_DOMAIN, other)
        return DomainCall(sequence, "", 1, len(sequence), (), None, other)
    if len(families) > 1 and not cfg.get("allow_mixed_families", False):
        return DomainCall(
            None, ", ".join(sorted(families)), 0, 0, tuple(hits), MIXED_FAMILIES, other
        )
    if len(hits) > 1 and not cfg.get("allow_repeat_arrays", False):
        return DomainCall(None, next(iter(families)), 0, 0, tuple(hits), REPEAT_ARRAY, other)

    lo = max(1, min(h.start for h in hits) - pad)
    hi = min(len(sequence), max(h.end for h in hits) + pad)
    return DomainCall(sequence[lo - 1 : hi], next(iter(families)), lo, hi, tuple(hits), None, other)


def audit_variant_positions(call: DomainCall, mut_positions: list[int]) -> list[int]:
    """Condition 3: return the mutation positions that fall outside the stored region.

    A non-empty result means the variant would be sequence-identical to its wild type once
    trimmed, which is exactly the failure the padding exists to prevent.
    """
    if not call.ok:
        return list(mut_positions)
    return [p for p in mut_positions if not (call.start <= p <= call.end)]


def rebase_positions(call: DomainCall, mut_positions: list[int]) -> list[int]:
    """Re-express construct positions as 1-based positions within the stored `dbd_seq`."""
    return [p - call.start + 1 for p in mut_positions]
