"""DNA-binding domain annotation, and the admission policy for what may enter the dataset.

**`dbd_seq` is the Pfam envelope padded by `domain.padding_aa` residues on each side, not
the bare envelope.** See `configs/thresholds.yaml` and `docs/DOMAIN_POLICY.md` for why.

A construct is admitted only if the stored subunit satisfies all three conditions:

1. **Sole responsibility** — it alone produced the measured interaction. A construct whose
   Pfam hits span two families (PAX+homeodomain, POU+homeodomain) fails: two domains bind,
   and nothing in the data says which produced a given 8-mer's score.
2. **One continuous region** — not fragments scattered through the protein. A C2H2 array is
   2-6 separate ~23-residue folds on flexible linkers, each needing its own Zn(2+), so it
   fails even though every finger belongs to one family.
3. **The variation lies inside it** — a mutation outside the stored region makes a variant
   sequence-identical to its wild type while carrying a different label. Padding exists to
   satisfy this condition, and `audit_variant_positions` checks it directly.

Rejections are reported, never silently repaired.

**Scanning uses the full Pfam-A library, not a hand-picked subset.** An earlier version
carried HMMs only for the nine families present in the first four sources, which meant
constructs from other families were rejected as `no_domain` because the HMM was missing
rather than because nothing was there. UniPROBE spans 86 distinct domain labels.

Because a full-Pfam scan also finds domains that have nothing to do with DNA, the admission
policy is evaluated over **DNA-binding families only** (`dbd_families.txt`). A DBD sitting
beside an unrelated domain still satisfies condition 1 — that DBD is solely responsible for
the DNA interaction — so non-DBD hits are recorded on the call and otherwise ignored.
"""

from __future__ import annotations

import functools
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pyhmmer
from pyhmmer.easel import Alphabet, TextSequence

from snp2prot import thresholds
from snp2prot.config import PROJECT_ROOT


class Rejection(str):
    """Why a construct was not admitted. A plain string so it lands in reports unchanged."""


MIXED_FAMILIES = Rejection("mixed_families")
REPEAT_ARRAY = Rejection("repeat_array")
NO_DOMAIN = Rejection("no_domain")
UNRESOLVED_RESIDUE = Rejection("unresolved_residue")

#: The 20 standard residues. Anything else in a stored `dbd_seq` is an unresolved position
#: from the depositor's own record, not a property of the protein: `X`, `B`, `Z` and `U` say
#: "not determined". One domain in the corpus carried two (`MAR17A:Esrrb`, 89 aa zf-C4) and
#: was excluded on 2026-08-18 (`docs/DECISIONS.md`, `D2`) — a sequence model would embed the
#: ambiguity as a token and a structure predictor cannot place the residue at all.
STANDARD_RESIDUES = frozenset("ACDEFGHIKLMNPQRSTVWY")


@dataclass(frozen=True)
class DomainHit:
    family: str
    start: int  # 1-based, inclusive, in the scanned sequence
    end: int
    score: float = 0.0

    @property
    def length(self) -> int:
        return self.end - self.start + 1


@dataclass(frozen=True)
class DomainCall:
    """The admission decision for one construct."""

    sequence: str | None  # the padded domain, or None if rejected
    family: str
    start: int
    end: int
    hits: tuple[DomainHit, ...]
    rejection: Rejection | None = None
    #: Non-DNA-binding Pfam hits found in the same construct. Recorded, not acted on.
    other: tuple[DomainHit, ...] = ()

    @property
    def ok(self) -> bool:
        return self.rejection is None


def _name(x: Any) -> str:
    return x.decode() if isinstance(x, bytes) else str(x)


@functools.lru_cache(maxsize=1)
def dbd_families(path: str | None = None) -> frozenset[str]:
    """Pfam family names that are DNA-binding domains.

    Generated by `scripts/build_dbd_family_list.py` from the domain labels UniPROBE itself
    publishes, resolved against Pfam-A's own NAME fields. Only these families are considered
    when applying the admission policy.
    """
    cfg = thresholds.load()["domain"]
    f = Path(path or cfg["dbd_families"])
    if not f.is_absolute():
        f = PROJECT_ROOT / f
    if not f.exists():
        raise FileNotFoundError(f"DBD family list not found: {f}")
    return frozenset(
        line.split("#")[0].strip()
        for line in f.read_text().splitlines()
        if line.strip() and not line.startswith("#")
    )


def _hmm_path() -> Path:
    cfg = thresholds.load()["domain"]
    p = Path(cfg["hmm_db"])
    if not p.is_absolute():
        p = PROJECT_ROOT / p
    if not p.exists():
        raise FileNotFoundError(f"Pfam HMM library not found: {p}")
    return p


@functools.lru_cache(maxsize=2)
def _library(path: str) -> Any:
    """Load an HMM library once per process and hold it ready to scan against.

    Every source used to reopen the library, and for the full Pfam-A that is 2.2 GB of text
    parsed from scratch per accession -- 19.5 s each, against ~0.1 s of actual scanning, so a
    30-source build spent roughly ten minutes re-reading one unchanging file.

    **Press the library** (`scripts/press_pfam.py`, or `hmmpress`). Pressed, HMMER's binary
    siblings carry profiles already optimized, so they are read straight into an
    `OptimizedProfileBlock` in ~0.5 s and each subsequent scan costs ~0.6 s. Unpressed we can
    still avoid re-parsing the text, but the profiles must be configured on every scan, which
    is ~6x slower per source and why the unpressed path says so out loud.

    Holding the block costs ~1.6 GB of RSS for Pfam-A, which is the whole point: it is paid
    once instead of thirty times. Cached by path, so a test HMM and the full library can both
    be live without evicting each other. A library re-pressed mid-process is not noticed --
    nothing in this project does that, and a new interpreter clears the cache.
    """
    abc = Alphabet.amino()
    with pyhmmer.plan7.HMMFile(path) as hmms:
        if hmms.is_pressed():
            return pyhmmer.plan7.OptimizedProfileBlock(abc, hmms.optimized_profiles())
        if Path(path).stat().st_size > 100_000_000:
            print(
                f"note: {path} is not pressed, so every scan reconfigures {30_134:,}-odd "
                f"profiles. Run scripts/press_pfam.py once to make this ~6x faster."
            )
        return list(hmms)


def scan(
    sequences: dict[str, str], hmm_path: str | Path | None = None, cpus: int = 0
) -> dict[str, list[DomainHit]]:
    """Pfam-scan many sequences against the full library, using each family's own threshold.

    Returns every hit, DNA-binding or not; `call_domain` decides which ones the policy sees.

    The library is loaded once per process and reused -- see `_library`. Scanning itself is
    cheap and barely scales with input: 3 sequences and 100 sequences cost the same, because
    essentially all of the work is in the library, not the queries.
    """
    abc = Alphabet.amino()
    keys = list(sequences)
    queries = [TextSequence(name=k.encode(), sequence=sequences[k]).digitize(abc) for k in keys]
    found: dict[str, list[DomainHit]] = {k: [] for k in keys}
    path = Path(hmm_path) if hmm_path else _hmm_path()
    library = _library(str(path.resolve()))
    for top in pyhmmer.hmmer.hmmscan(queries, library, bit_cutoffs="gathering", cpus=cpus):
        name = _name(top.query.name)
        for hit in top:
            for dom in hit.domains.included:
                # In hmmscan the roles are swapped relative to a per-family search, but
                # pyhmmer still reports target_from/to in sequence coordinates. Verified
                # against ARX, which gives Homeodomain[15-71] either way.
                found[name].append(
                    DomainHit(
                        _name(hit.name),
                        dom.alignment.target_from,
                        dom.alignment.target_to,
                        float(dom.score),
                    )
                )
    return {k: sorted(v, key=lambda h: h.start) for k, v in found.items()}


#: Pfam model names that denote the same biological family, mapped to one label so that
#: `dbd_family` is a family and not a model id. Without this, `bZIP_1` and `bZIP_2` — two
#: models of one basic-leucine-zipper — split the family across two labels depending on which
#: scored higher per protein, and a family-level split would never see bZIP as one group.
#: Deliberately minimal: `TF_AP-2` (mammalian TFAP2) and `AP2` (plant AP2/ERF) are different
#: domains that merely look alike by name, and are NOT merged.
FAMILY_ALIASES = {
    "bZIP_1": "bZIP",
    "bZIP_2": "bZIP",
    "zf-H2C2_2": "zf-C2H2",
    "Homeobox_KN": "Homeodomain",
    "SOXp": "HMG_box",
}


def canonical_family(name: str) -> str:
    return FAMILY_ALIASES.get(name, name)


#: Two hits covering this much of the shorter one are taken to describe a single domain.
COLOCATION_OVERLAP = 0.5


def collapse_colocated(hits: list[DomainHit]) -> list[DomainHit]:
    """Merge hits from different families that cover the same region.

    Pfam sometimes models one domain with several families. `bZIP_1` and `bZIP_2` both match
    the same basic-leucine-zipper, `zf-H2C2_2` overlaps `zf-C2H2`, and `Homeodomain` overlaps
    `Homeobox_KN`. Left alone these look like two domains in one construct and the
    `mixed_families` rule rejects the protein — which cost us most of the bZIP family before
    this was noticed, one of the three families the brief asks for by name.

    Overlapping hits are one domain described twice, so the highest-scoring is kept and the
    rest dropped. Hits that merely sit near each other are untouched: a real two-domain
    construct (PAX + homeodomain) has them well separated, and must still be rejected.
    """
    kept: list[DomainHit] = []
    for h in sorted(hits, key=lambda x: (-x.score, -x.length)):
        clash = False
        for k in kept:
            overlap = max(0, min(h.end, k.end) - max(h.start, k.start) + 1)
            if overlap / min(h.length, k.length) > COLOCATION_OVERLAP:
                clash = True
                break
        if not clash:
            kept.append(h)
    return sorted(kept, key=lambda x: x.start)


def call_domain(
    sequence: str, hits: list[DomainHit], config: dict[str, Any] | None = None
) -> DomainCall:
    """Apply the admission policy to one construct and return the padded domain."""
    cfg = config or thresholds.load()["domain"]
    pad = int(cfg["padding_aa"])

    # Only DNA-binding families take part in the policy. A construct carrying a homeodomain
    # plus, say, a LIM or PWWP domain is still attributable: the homeodomain is what binds.
    known = dbd_families()
    other = tuple(h for h in hits if h.family not in known)
    hits = collapse_colocated(
        [
            DomainHit(canonical_family(h.family), h.start, h.end, h.score)
            for h in hits
            if h.family in known
        ]
    )
    families = {h.family for h in hits}

    if not hits:
        if not cfg.get("allow_no_domain", False):
            return DomainCall(None, "", 0, 0, (), NO_DOMAIN, other)
        return DomainCall(sequence, "", 1, len(sequence), (), None, other)
    if len(families) > 1 and not cfg.get("allow_mixed_families", False):
        return DomainCall(
            None, ", ".join(sorted(families)), 0, 0, tuple(hits), MIXED_FAMILIES, other
        )
    if len(hits) > 1 and not cfg.get("allow_repeat_arrays", False):
        return DomainCall(None, next(iter(families)), 0, 0, tuple(hits), REPEAT_ARRAY, other)

    lo = max(1, min(h.start for h in hits) - pad)
    hi = min(len(sequence), max(h.end for h in hits) + pad)
    window = sequence[lo - 1 : hi]
    family = next(iter(families))
    if set(window) - STANDARD_RESIDUES:
        return DomainCall(None, family, 0, 0, tuple(hits), UNRESOLVED_RESIDUE, other)
    return DomainCall(window, family, lo, hi, tuple(hits), None, other)


def audit_variant_positions(call: DomainCall, mut_positions: list[int]) -> list[int]:
    """Condition 3: return the mutation positions that fall outside the stored region.

    A non-empty result means the variant would be sequence-identical to its wild type once
    trimmed, which is exactly the failure the padding exists to prevent.
    """
    if not call.ok:
        return list(mut_positions)
    return [p for p in mut_positions if not (call.start <= p <= call.end)]


def rebase_positions(call: DomainCall, mut_positions: list[int]) -> list[int]:
    """Re-express construct positions as 1-based positions within the stored `dbd_seq`."""
    return [p - call.start + 1 for p in mut_positions]
