"""Generation of the markdown reports under `reports/`.

These are review artifacts for the project owner, not logs: each is regenerated from the
tables and committed, so a diff shows how the dataset changed between phases.

- `binarization_summary_<source>.md` — n_pos / n_neg / n_gray, positive rate, and the
  `raw_score` distribution with the applied cutoffs marked (brief section 4).
- `cluster_inventory.md`  — per `wt_id`: variant count and `n_mut_from_wt` distribution;
  per family: cluster count. Flags any family contributing >40% of rows (brief section 5b).
- `overlap.md`            — (dbd_seq, dna_seq) pairs seen in more than one source and
  whether their labels agree; the disagreement rate reads directly as label noise.

Histograms are rendered as text rather than PNGs on purpose: these files are committed, and
a text histogram diffs legibly while a binary image does not.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from snp2prot import schema

#: A family above this share of total rows gets flagged — C2H2 will otherwise swamp
#: everything and the model can win by memorizing one family.
FAMILY_DOMINANCE_FLAG = 0.40


def _fmt(n: int) -> str:
    return f"{n:,}"


def binarization_summary(df: pd.DataFrame, source: str) -> str:
    """Label counts and the score distribution against the cutoffs actually applied."""
    pos_cut = float(df["threshold_pos"].iloc[0])
    neg_cut = float(df["threshold_neg"].iloc[0])
    scores = df["raw_score"].to_numpy(dtype=float)
    counts = df["label"].value_counts()
    n_pos = int(counts.get(schema.LABEL_BIND, 0))
    n_neg = int(counts.get(schema.LABEL_NONBIND, 0))
    n_gray = int(counts.get(schema.LABEL_GRAY, 0))
    n = len(df)

    lines = [
        f"# Binarization summary — {source}",
        "",
        "Regenerated by `scripts/make_reports.py`. Do not hand-edit.",
        "",
        "## Cutoffs applied",
        "",
        f"- score type: `{df['score_type'].iloc[0]}`",
        f"- positive: `raw_score >= {pos_cut}`",
        f"- negative: `raw_score <= {neg_cut}`",
        "- between the two: label `-1`, kept in the table and excluded from training",
        "",
        "## Label counts",
        "",
        "| label | meaning | rows | share |",
        "|---|---|---:|---:|",
        f"| `1` | binds | {_fmt(n_pos)} | {n_pos / n:.4%} |",
        f"| `0` | does not bind | {_fmt(n_neg)} | {n_neg / n:.4%} |",
        f"| `-1` | gray band, excluded | {_fmt(n_gray)} | {n_gray / n:.4%} |",
        f"| | **total** | **{_fmt(n)}** | |",
        "",
        f"Negative:positive ratio **{n_neg / n_pos:.0f}:1**." if n_pos else "No positives.",
        "",
        "## Negative provenance",
        "",
        "| provenance | rows |",
        "|---|---:|",
    ]
    neg_prov = df.loc[df["label"] == schema.LABEL_NONBIND, "neg_provenance"].value_counts()
    for k, v in neg_prov.items():
        lines.append(f"| `{k}` | {_fmt(int(v))} |")

    lines += [
        "",
        "## Score distribution",
        "",
        f"Full range observed: `{scores.min():.4f}` to `{scores.max():.4f}`.",
        "Bin edges are lower bounds; `<` and `>` mark the two cutoffs.",
        "",
        "```",
    ]
    lo, hi = float(np.floor(scores.min() * 20) / 20), float(np.ceil(scores.max() * 20) / 20)
    counts_h, edges = np.histogram(scores, bins=40, range=(lo, hi))
    peak = counts_h.max() or 1
    for i, c in enumerate(counts_h):
        mark = " "
        if edges[i] <= neg_cut < edges[i + 1]:
            mark = "<"
        if edges[i] <= pos_cut < edges[i + 1]:
            mark = ">"
        bar = "#" * max(1, round(54 * c / peak)) if c else ""
        lines.append(f"{edges[i]:+.3f} {mark}| {bar} {_fmt(int(c))}")
    lines += ["```", ""]
    return "\n".join(lines)


def cluster_inventory(df: pd.DataFrame, source: str | None = None) -> str:
    """Per-cluster and per-family structure — the lookup-table risk, quantified."""
    title = f"# Cluster inventory{f' — {source}' if source else ''}"
    n = len(df)

    # One row per distinct DBD, so cluster sizes count proteins rather than measurements.
    dbds = df[["wt_id", "dbd_seq", "dbd_family", "n_mut_from_wt"]].drop_duplicates("dbd_seq")
    per_cluster = (
        dbds.groupby("wt_id")
        .agg(
            family=("dbd_family", "first"),
            n_dbds=("dbd_seq", "size"),
            has_wt=("n_mut_from_wt", lambda s: bool((s == 0).any())),
            max_mut=("n_mut_from_wt", "max"),
        )
        .sort_values("n_dbds", ascending=False)
    )
    rows_per_cluster = df.groupby("wt_id").size()

    lines = [
        title,
        "",
        "Regenerated by `scripts/make_reports.py`. Do not hand-edit.",
        "",
        "## Totals",
        "",
        f"- rows: **{_fmt(n)}**",
        f"- clusters (`wt_id`): **{_fmt(len(per_cluster))}**",
        f"- distinct DBD sequences: **{_fmt(df['dbd_seq'].nunique())}**",
        f"- distinct DNA sites: **{_fmt(df['dna_seq'].nunique())}**",
        f"- clusters missing their reference DBD: **{int((~per_cluster['has_wt']).sum())}**",
        "",
        "## Variants per cluster",
        "",
        "`n_dbds` counts the reference plus its variants.",
        "",
        "| distinct DBDs in cluster | clusters |",
        "|---:|---:|",
    ]
    for k, v in per_cluster["n_dbds"].value_counts().sort_index().items():
        lines.append(f"| {k} | {v} |")

    lines += [
        "",
        "## Hamming distance from the reference",
        "",
        "| n_mut_from_wt | distinct DBDs |",
        "|---:|---:|",
    ]
    for k, v in dbds["n_mut_from_wt"].value_counts().sort_index().items():
        lines.append(f"| {k} | {_fmt(int(v))} |")

    fam_rows = df.groupby("dbd_family").size().sort_values(ascending=False)
    fam_clusters = per_cluster.groupby("family").size()
    lines += [
        "",
        "## Families",
        "",
        f"A family above {FAMILY_DOMINANCE_FLAG:.0%} of rows is flagged: it can be memorized "
        "instead of learned.",
        "",
        "| family | clusters | distinct DBDs | rows | share of rows | |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for fam, rows in fam_rows.items():
        share = rows / n
        flag = " **FLAG**" if share > FAMILY_DOMINANCE_FLAG else ""
        n_dbd_fam = int(dbds.loc[dbds["dbd_family"] == fam, "dbd_seq"].nunique())
        lines.append(
            f"| `{fam}` | {int(fam_clusters.get(fam, 0))} | {n_dbd_fam} | "
            f"{_fmt(int(rows))} | {share:.1%} |{flag} |"
        )

    lines += [
        "",
        "## Clusters",
        "",
        "| wt_id | family | distinct DBDs | rows | reference present |",
        "|---|---|---:|---:|:-:|",
    ]
    for wt_id, r in per_cluster.iterrows():
        lines.append(
            f"| `{wt_id}` | `{r['family']}` | {int(r['n_dbds'])} | "
            f"{_fmt(int(rows_per_cluster[wt_id]))} | {'yes' if r['has_wt'] else 'NO'} |"
        )
    lines.append("")
    return "\n".join(lines)


#: A cross-source replicate below this positive-call Jaccard is reported as suspect rather
#: than as noise. Two labs assaying one domain against one 8-mer set should agree on which
#: 8-mers bind; near-zero overlap is what a mislabelled construct looks like, not what
#: measurement error looks like.
REPLICATE_JACCARD_FLAG = 0.20

#: Likewise for rank agreement on the raw E-score, which is threshold-independent and so
#: separates "the cutoff fell in a different place" from "these are different measurements".
REPLICATE_RHO_FLAG = 0.30


def _spearman(a: pd.Series, b: pd.Series) -> float:
    """Rank correlation without scipy — pandas' `method="spearman"` imports it."""
    return float(a.rank().corr(b.rank()))


def _replicate_pairs(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    """One row per (dbd_seq, source A, source B) where two sources measured one domain."""
    seen: dict[str, set[str]] = {}
    for source, df in frames.items():
        for seq in df["dbd_seq"].unique():
            seen.setdefault(seq, set()).add(source)

    rows = []
    for seq, sources in seen.items():
        if len(sources) < 2:
            continue
        ordered = sorted(sources)
        for i, a in enumerate(ordered):
            for b in ordered[i + 1 :]:
                fa = frames[a]
                fb = frames[b]
                A = fa[fa["dbd_seq"] == seq].drop_duplicates("dna_seq").set_index("dna_seq")
                B = fb[fb["dbd_seq"] == seq].drop_duplicates("dna_seq").set_index("dna_seq")
                common = A.index.intersection(B.index)
                A, B = A.loc[common], B.loc[common]

                la, lb = A["label"].to_numpy(), B["label"].to_numpy()
                # -1 is the gray zone between the two cutoffs: no call was made, so it is
                # not evidence of disagreement.
                hard = (la != -1) & (lb != -1)
                pos_a, pos_b = la == 1, lb == 1
                union = int((pos_a | pos_b).sum())
                rows.append(
                    {
                        "dbd_seq": seq,
                        "wt_id": A["wt_id"].iloc[0],
                        "family": A["dbd_family"].iloc[0],
                        "a": a,
                        "b": b,
                        "n_common": len(common),
                        "n_hard": int(hard.sum()),
                        "agree": float((la[hard] == lb[hard]).mean())
                        if hard.any()
                        else float("nan"),
                        "pos_a": int(pos_a.sum()),
                        "pos_b": int(pos_b.sum()),
                        "pos_both": int((pos_a & pos_b).sum()),
                        "jaccard": float((pos_a & pos_b).sum() / union) if union else float("nan"),
                        "rho": _spearman(A["raw_score"], B["raw_score"]),
                    }
                )
    if not rows:
        return pd.DataFrame(columns=["dbd_seq", "wt_id", "family", "a", "b", "jaccard", "rho"])
    return pd.DataFrame(rows).sort_values(["jaccard", "rho"]).reset_index(drop=True)


def overlap_report(frames: dict[str, pd.DataFrame]) -> str:
    """Cross-source replicates and how far their labels agree.

    `frames` maps source name to that source's rows. Only domains present in more than one
    source contribute, so the caller may pass frames pre-filtered to those domains.

    The headline is deliberately *not* the overall agreement rate. Positives are well under
    1% of rows, so agreeing on the negatives carries that number to ~100% no matter how
    badly the two labs agree on which 8-mers actually bind. The positive-call Jaccard is the
    number that means something.
    """
    r = _replicate_pairs(frames)
    lines = [
        "# Cross-source overlap — the label noise floor",
        "",
        "Regenerated by `scripts/make_overlap_report.py`. Do not hand-edit.",
        "",
    ]
    if r.empty:
        lines += ["No domain is measured by more than one source.", ""]
        return "\n".join(lines)

    n_seq = r["dbd_seq"].nunique()
    n_hard = int(r["n_hard"].sum())
    n_disagree = int(((1.0 - r["agree"]) * r["n_hard"]).round().sum())
    pooled_union = int((r["pos_a"] + r["pos_b"] - r["pos_both"]).sum())
    pooled_both = int(r["pos_both"].sum())

    lines += [
        f"**{n_seq} domains are measured by more than one source**, giving {len(r)} source "
        "pairs of the same protein against the same 8-mer set. Two labs, one sequence: the "
        "rate at which they disagree is a direct measurement of the label noise floor, and "
        "nothing else in the corpus provides it.",
        "",
        "## The headline",
        "",
        "| measure | value |",
        "|---|---|",
        f"| hard-label agreement (pooled) | {100 * (1 - n_disagree / n_hard):.3f}% "
        f"({_fmt(n_disagree)} of {_fmt(n_hard)} calls differ) |",
        f"| **positive-call Jaccard (median)** | **{r['jaccard'].median():.3f}** |",
        f"| positive-call Jaccard (min / max) | {r['jaccard'].min():.3f} / "
        f"{r['jaccard'].max():.3f} |",
        f"| positives agreed on (pooled) | {_fmt(pooled_both)} of {_fmt(pooled_union)} "
        f"({100 * pooled_both / pooled_union:.1f}%) |",
        f"| E-score rank correlation (median) | {r['rho'].median():.3f} |",
        f"| E-score rank correlation (min) | {r['rho'].min():.3f} |",
        "",
        "**Read the second row, not the first.** Positives are a fraction of a percent of "
        "every 8-mer table, so two labs agreeing that the other 99.6% does not bind pins the "
        "pooled agreement near 100% however badly they agree about binding. On the calls the "
        "dataset exists to make, the median replicate pair agrees on "
        f"{100 * r['jaccard'].median():.0f}% of the 8-mers either of them called positive.",
        "",
    ]

    flagged = r[(r["jaccard"] < REPLICATE_JACCARD_FLAG) | (r["rho"] < REPLICATE_RHO_FLAG)]
    lines += [
        "## Flagged replicates",
        "",
        f"Jaccard below {REPLICATE_JACCARD_FLAG} or rank correlation below "
        f"{REPLICATE_RHO_FLAG}. These are reported, never repaired: a replicate this far "
        "apart is more likely a construct assigned to the wrong measurement than a lab "
        "disagreeing with itself.",
        "",
    ]
    if flagged.empty:
        lines += ["None.", ""]
    else:
        lines += [
            "| `wt_id` | family | A | B | pos A | pos B | both | Jaccard | rho |",
            "|---|---|---|---|---:|---:|---:|---:|---:|",
        ]
        for _, x in flagged.iterrows():
            lines.append(
                f"| `{x['wt_id']}` | `{x['family']}` | {x['a']} | {x['b']} | {x['pos_a']} | "
                f"{x['pos_b']} | {x['pos_both']} | {x['jaccard']:.3f} | {x['rho']:.3f} |"
            )
        lines.append("")

    lines += [
        "## Every replicate pair",
        "",
        "Sorted by positive-call agreement, worst first.",
        "",
        "| `wt_id` | family | A | B | 8-mers | hard calls | agree | pos A | pos B | both |"
        " Jaccard | rho |",
        "|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for _, x in r.iterrows():
        lines.append(
            f"| `{x['wt_id']}` | `{x['family']}` | {x['a']} | {x['b']} | "
            f"{_fmt(int(x['n_common']))} | {_fmt(int(x['n_hard']))} | {100 * x['agree']:.3f}% | "
            f"{x['pos_a']} | {x['pos_b']} | {x['pos_both']} | {x['jaccard']:.3f} | "
            f"{x['rho']:.3f} |"
        )
    lines.append("")
    return "\n".join(lines)
