"""Generation of the markdown reports under `reports/`.

These are review artifacts for the project owner, not logs: each is regenerated from the
tables and committed, so a diff shows how the dataset changed between phases.

- `binarization_summary_<source>.md` — n_pos / n_neg / n_gray, positive rate, and the
  `raw_score` distribution with the applied cutoffs marked (brief section 4).
- `cluster_inventory.md`  — per `wt_id`: variant count and `n_mut_from_wt` distribution;
  per family: cluster count. Flags any family contributing >40% of rows (brief section 5b).
- `overlap.md`            — (dbd_seq, dna_seq) pairs seen in more than one source and
  whether their labels agree; the disagreement rate reads directly as label noise.

Histograms are rendered as text rather than PNGs on purpose: these files are committed, and
a text histogram diffs legibly while a binary image does not.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from snp2prot import schema

#: A family above this share of total rows gets flagged — C2H2 will otherwise swamp
#: everything and the model can win by memorizing one family.
FAMILY_DOMINANCE_FLAG = 0.40


def _fmt(n: int) -> str:
    return f"{n:,}"


def binarization_summary(df: pd.DataFrame, source: str) -> str:
    """Label counts and the score distribution against the cutoffs actually applied."""
    pos_cut = float(df["threshold_pos"].iloc[0])
    neg_cut = float(df["threshold_neg"].iloc[0])
    scores = df["raw_score"].to_numpy(dtype=float)
    counts = df["label"].value_counts()
    n_pos = int(counts.get(schema.LABEL_BIND, 0))
    n_neg = int(counts.get(schema.LABEL_NONBIND, 0))
    n_gray = int(counts.get(schema.LABEL_GRAY, 0))
    n = len(df)

    lines = [
        f"# Binarization summary — {source}",
        "",
        "Regenerated by `scripts/make_reports.py`. Do not hand-edit.",
        "",
        "## Cutoffs applied",
        "",
        f"- score type: `{df['score_type'].iloc[0]}`",
        f"- positive: `raw_score >= {pos_cut}`",
        f"- negative: `raw_score <= {neg_cut}`",
        "- between the two: label `-1`, kept in the table and excluded from training",
        "",
        "## Label counts",
        "",
        "| label | meaning | rows | share |",
        "|---|---|---:|---:|",
        f"| `1` | binds | {_fmt(n_pos)} | {n_pos / n:.4%} |",
        f"| `0` | does not bind | {_fmt(n_neg)} | {n_neg / n:.4%} |",
        f"| `-1` | gray band, excluded | {_fmt(n_gray)} | {n_gray / n:.4%} |",
        f"| | **total** | **{_fmt(n)}** | |",
        "",
        f"Negative:positive ratio **{n_neg / n_pos:.0f}:1**." if n_pos else "No positives.",
        "",
        "## Negative provenance",
        "",
        "| provenance | rows |",
        "|---|---:|",
    ]
    neg_prov = df.loc[df["label"] == schema.LABEL_NONBIND, "neg_provenance"].value_counts()
    for k, v in neg_prov.items():
        lines.append(f"| `{k}` | {_fmt(int(v))} |")

    lines += [
        "",
        "## Score distribution",
        "",
        f"Full range observed: `{scores.min():.4f}` to `{scores.max():.4f}`.",
        "Bin edges are lower bounds; `<` and `>` mark the two cutoffs.",
        "",
        "```",
    ]
    lo, hi = float(np.floor(scores.min() * 20) / 20), float(np.ceil(scores.max() * 20) / 20)
    counts_h, edges = np.histogram(scores, bins=40, range=(lo, hi))
    peak = counts_h.max() or 1
    for i, c in enumerate(counts_h):
        mark = " "
        if edges[i] <= neg_cut < edges[i + 1]:
            mark = "<"
        if edges[i] <= pos_cut < edges[i + 1]:
            mark = ">"
        bar = "#" * max(1, round(54 * c / peak)) if c else ""
        lines.append(f"{edges[i]:+.3f} {mark}| {bar} {_fmt(int(c))}")
    lines += ["```", ""]
    return "\n".join(lines)


def cluster_inventory(df: pd.DataFrame, source: str | None = None) -> str:
    """Per-cluster and per-family structure — the lookup-table risk, quantified."""
    title = f"# Cluster inventory{f' — {source}' if source else ''}"
    n = len(df)

    # One row per distinct DBD, so cluster sizes count proteins rather than measurements.
    dbds = df[["wt_id", "dbd_seq", "dbd_family", "n_mut_from_wt"]].drop_duplicates("dbd_seq")
    per_cluster = (
        dbds.groupby("wt_id")
        .agg(
            family=("dbd_family", "first"),
            n_dbds=("dbd_seq", "size"),
            has_wt=("n_mut_from_wt", lambda s: bool((s == 0).any())),
            max_mut=("n_mut_from_wt", "max"),
        )
        .sort_values("n_dbds", ascending=False)
    )
    rows_per_cluster = df.groupby("wt_id").size()

    lines = [
        title,
        "",
        "Regenerated by `scripts/make_reports.py`. Do not hand-edit.",
        "",
        "## Totals",
        "",
        f"- rows: **{_fmt(n)}**",
        f"- clusters (`wt_id`): **{_fmt(len(per_cluster))}**",
        f"- distinct DBD sequences: **{_fmt(df['dbd_seq'].nunique())}**",
        f"- distinct DNA sites: **{_fmt(df['dna_seq'].nunique())}**",
        f"- clusters missing their reference DBD: **{int((~per_cluster['has_wt']).sum())}**",
        "",
        "## Variants per cluster",
        "",
        "`n_dbds` counts the reference plus its variants.",
        "",
        "| distinct DBDs in cluster | clusters |",
        "|---:|---:|",
    ]
    for k, v in per_cluster["n_dbds"].value_counts().sort_index().items():
        lines.append(f"| {k} | {v} |")

    lines += [
        "",
        "## Hamming distance from the reference",
        "",
        "| n_mut_from_wt | distinct DBDs |",
        "|---:|---:|",
    ]
    for k, v in dbds["n_mut_from_wt"].value_counts().sort_index().items():
        lines.append(f"| {k} | {_fmt(int(v))} |")

    fam_rows = df.groupby("dbd_family").size().sort_values(ascending=False)
    fam_clusters = per_cluster.groupby("family").size()
    lines += [
        "",
        "## Families",
        "",
        f"A family above {FAMILY_DOMINANCE_FLAG:.0%} of rows is flagged: it can be memorized "
        "instead of learned.",
        "",
        "| family | clusters | distinct DBDs | rows | share of rows | |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for fam, rows in fam_rows.items():
        share = rows / n
        flag = " **FLAG**" if share > FAMILY_DOMINANCE_FLAG else ""
        n_dbd_fam = int(dbds.loc[dbds["dbd_family"] == fam, "dbd_seq"].nunique())
        lines.append(
            f"| `{fam}` | {int(fam_clusters.get(fam, 0))} | {n_dbd_fam} | "
            f"{_fmt(int(rows))} | {share:.1%} |{flag} |"
        )

    lines += [
        "",
        "## Clusters",
        "",
        "| wt_id | family | distinct DBDs | rows | reference present |",
        "|---|---|---:|---:|:-:|",
    ]
    for wt_id, r in per_cluster.iterrows():
        lines.append(
            f"| `{wt_id}` | `{r['family']}` | {int(r['n_dbds'])} | "
            f"{_fmt(int(rows_per_cluster[wt_id]))} | {'yes' if r['has_wt'] else 'NO'} |"
        )
    lines.append("")
    return "\n".join(lines)


def overlap_report(frames: dict[str, pd.DataFrame]) -> str:
    raise NotImplementedError("Phase 5")
