"""Unified row schema for every parsed binding dataset, plus its validator.

Every parser in `snp2prot.parsers` returns a DataFrame with exactly these columns, in this
order, and every such DataFrame must pass `validate()` before it is written to
`data/interim/`. The schema is defined once, here — parsers never declare their own columns.

Reference: docs/TFDNA_MERGE_BRIEF.md §3.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from typing import Any, ClassVar

import pandas as pd

# --------------------------------------------------------------------------------------
# Controlled vocabularies
# --------------------------------------------------------------------------------------

#: `label` values. -1 is the gray band: rows kept in the table but excluded from training.
LABEL_BIND = 1
LABEL_NONBIND = 0
LABEL_GRAY = -1
VALID_LABELS = frozenset({LABEL_BIND, LABEL_NONBIND, LABEL_GRAY})

#: Was real flanking sequence observed around the site, or only the core?
VALID_DNA_CONTEXT = frozenset({"full", "core_only"})

#: How a negative came to be a negative. Mandatory on every `label == 0` row.
#: `assayed_unbound`  — the sequence was measured and scored below threshold (e.g. PBM E-score).
#: `selection_absent` — the sequence simply never came out of a selection. Weak evidence.
#: `synthetic`        — generated by us (e.g. dinucleotide shuffle). Not yet used.
VALID_NEG_PROVENANCE = frozenset({"assayed_unbound", "selection_absent", "synthetic"})

#: Amino acids permitted in `dbd_seq`. `X` is allowed for genuinely unresolved residues only.
AA_ALPHABET = frozenset("ACDEFGHIKLMNPQRSTVWYX")

#: Bases permitted in `dna_seq`. Strictly unambiguous — degenerate codes and pad characters
#: are a parse error, not something to tolerate silently (brief §3, "no padding characters").
DNA_ALPHABET = frozenset("ACGT")
#: The 20 standard residues; `X`/`B`/`Z`/`U` mean "not determined" and must not reach a
#: stored domain (`docs/DECISIONS.md`, `D2`).
PROTEIN_ALPHABET = frozenset("ACDEFGHIKLMNPQRSTVWY")

#: Hard cap from the brief: nothing longer than 20 bp reaches the stored table.
MAX_DNA_LEN = 20


# --------------------------------------------------------------------------------------
# Column definition
# --------------------------------------------------------------------------------------


@dataclass(frozen=True)
class Column:
    name: str
    dtype: str
    required: bool
    doc: str


COLUMNS: tuple[Column, ...] = (
    Column("pair_id", "string", True, "sha256 of (dbd_seq, dna_seq, assay, stringency)"),
    Column("dbd_seq", "string", True, "amino acids, DBD only, uppercase"),
    Column("dbd_family", "string", True, "CIS-BP/Pfam family, e.g. Homeodomain, C2H2 ZF"),
    Column("dbd_source", "string", True, "how the DBD boundaries were determined"),
    Column("wt_id", "string", True, "cluster key: the WT/reference domain this belongs to"),
    Column("n_mut_from_wt", "Int32", True, "Hamming distance to the WT sequence; 0 for WT"),
    Column("mut_positions", "string", False, "comma-separated, 1-based in DBD; empty for WT"),
    Column("protein_id", "string", False, "UniProt/gene identifier where known"),
    Column("species", "string", False, "source organism"),
    Column("dna_seq", "string", True, "observed bases only, <=20 bp, no padding"),
    Column("dna_len", "Int32", True, "len(dna_seq)"),
    Column("dna_context", "string", True, "full | core_only"),
    Column("label", "Int8", True, "1 bind, 0 non-bind, -1 gray band"),
    Column("raw_score", "Float64", True, "whatever the source measures"),
    Column("score_type", "string", True, "pbm_escore, b1h_sscore, snpselex_obs, dG_kcal, ..."),
    Column("threshold_pos", "Float64", True, "positive cutoff actually applied to this row"),
    Column("threshold_neg", "Float64", True, "negative cutoff actually applied to this row"),
    Column("assay", "string", True, "PBM, B1H, SNP-SELEX, MITOMI, ..."),
    Column("stringency", "string", False, "e.g. 2mM_3AT, 10mM_3AT; empty where not applicable"),
    Column("neg_provenance", "string", False, "required when label == 0; see VALID_NEG_PROVENANCE"),
    Column("source_dataset", "string", True, "BAR15A, persikov2015, ..."),
    Column("source_file", "string", True, "path relative to data/raw/"),
)

COLUMN_NAMES: tuple[str, ...] = tuple(c.name for c in COLUMNS)
DTYPES: dict[str, str] = {c.name: c.dtype for c in COLUMNS}

#: Columns whose combination defines row identity (mirrors the pair_id hash inputs).
PAIR_ID_KEYS: tuple[str, ...] = ("dbd_seq", "dna_seq", "assay", "stringency")

#: Columns a parser never supplies by hand — `coerce()` computes them from the others.
#: Supplying one anyway is allowed and then checked, so a parser cannot quietly disagree
#: with the derivation.
DERIVED = frozenset({"pair_id", "dna_len"})


#: Field separator inside the hashed payload. Keeps field boundaries unambiguous: without
#: it, ("AC", "DETAAT") and ("ACDE", "TAAT") would hash identically.
PAIR_ID_SEP = "\x1f"


def _hash_payload(payload: str) -> str:
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:24]


def make_pair_id(dbd_seq: str, dna_seq: str, assay: str, stringency: str = "") -> str:
    """Deterministic row identity. Stable across runs, machines, and pandas versions."""
    return _hash_payload(
        PAIR_ID_SEP.join((dbd_seq or "", dna_seq or "", assay or "", stringency or ""))
    )


def _as_str(value: Any) -> str:
    return "" if value is None or pd.isna(value) else str(value)


def add_pair_ids(df: pd.DataFrame) -> pd.DataFrame:
    """(Re)compute `pair_id` from the key columns.

    The payload is assembled with vectorized string concatenation rather than a Python loop.
    The loop it replaced called `pd.isna` four times per row -- 66 million calls over the
    corpus, for a check that `.fillna("")` does in one pass -- and this function runs twice
    per build, once in `coerce` and again in `validate`'s identity check. The hash itself is
    unchanged and still per row, because every row's payload is distinct by construction:
    2.8x faster, byte-identical output.
    """
    df = df.copy()
    empty = pd.Series([""] * len(df), index=df.index, dtype="string")
    parts = [
        (df[key].astype("string").fillna("") if key in df.columns else empty)
        for key in PAIR_ID_KEYS
    ]
    payload = parts[0]
    for part in parts[1:]:
        payload = payload + PAIR_ID_SEP + part
    df["pair_id"] = [_hash_payload(s) for s in payload]
    return df


def empty_frame() -> pd.DataFrame:
    """An empty DataFrame with the full schema and correct dtypes. Parsers build onto this."""
    return pd.DataFrame({c.name: pd.Series(dtype=c.dtype) for c in COLUMNS})


def coerce(df: pd.DataFrame) -> pd.DataFrame:
    """Reorder to the canonical column order, fill derived columns, and apply dtypes.

    This is the last call in every parser. Missing optional columns become nulls, the
    columns in `DERIVED` are computed, and unknown columns raise — a stray column is
    nearly always a parser that invented a field of its own.
    """
    unknown = [c for c in df.columns if c not in COLUMN_NAMES]
    if unknown:
        raise ValueError(f"columns not in the schema: {unknown}")

    out = df.copy()
    for col in COLUMNS:
        if col.name in out.columns:
            continue
        if col.required and col.name not in DERIVED:
            raise ValueError(f"required column missing: {col.name}")
        out[col.name] = pd.NA

    if out["dna_len"].isna().all():
        out["dna_len"] = out["dna_seq"].astype("string").str.len()
    if out["pair_id"].isna().all():
        out = add_pair_ids(out)

    out = out[list(COLUMN_NAMES)]
    return out.astype(DTYPES)


# --------------------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------------------


@dataclass
class ValidationReport:
    """Result of validating one parser's output.

    Errors block the write to `data/interim/`; warnings are surfaced but do not.
    """

    source: str
    n_rows: int = 0
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    stats: dict[str, Any] = field(default_factory=dict)

    MAX_EXAMPLES: ClassVar[int] = 5

    @property
    def ok(self) -> bool:
        return not self.errors

    def error(self, msg: str) -> None:
        self.errors.append(msg)

    def warn(self, msg: str) -> None:
        self.warnings.append(msg)

    def __str__(self) -> str:
        head = f"{'PASS' if self.ok else 'FAIL'} {self.source}: {self.n_rows:,} rows"
        lines = [head]
        lines += [f"  ERROR   {e}" for e in self.errors]
        lines += [f"  warning {w}" for w in self.warnings]
        return "\n".join(lines)

    def raise_if_failed(self) -> None:
        if not self.ok:
            raise SchemaValidationError(str(self))


class SchemaValidationError(Exception):
    """Raised when a parser's output violates the schema."""


def _examples(series: pd.Series, mask: pd.Series, n: int = 5) -> str:
    vals = series[mask].head(n).tolist()
    return ", ".join(repr(v) for v in vals)


def validate(
    df: pd.DataFrame, source: str = "<unnamed>", strict_wt: bool = True
) -> ValidationReport:
    """Check a parser's output against the schema.

    `strict_wt` also runs the cross-row cluster checks (every `wt_id` has a
    `n_mut_from_wt == 0` row, and all members share the WT's length). Disable it only when
    validating a deliberate subset of a larger table.
    """
    rep = ValidationReport(source=source, n_rows=len(df))

    # -- structure ---------------------------------------------------------------------
    if list(df.columns) != list(COLUMN_NAMES):
        missing = [c for c in COLUMN_NAMES if c not in df.columns]
        extra = [c for c in df.columns if c not in COLUMN_NAMES]
        if missing:
            rep.error(f"missing columns: {missing}")
        if extra:
            rep.error(f"unexpected columns: {extra}")
        if not missing and not extra:
            rep.error("columns present but in the wrong order; run schema.coerce()")
        return rep  # nothing below is meaningful without the right columns

    if len(df) == 0:
        rep.error("parser returned zero rows")
        return rep

    for col in COLUMNS:
        if col.required and df[col.name].isna().any():
            n = int(df[col.name].isna().sum())
            rep.error(f"{col.name}: {n:,} null values in a required column")

    # -- protein axis ------------------------------------------------------------------
    #
    # Every check below reads only columns that are CONSTANT within a construct: one
    # `dbd_seq` is repeated across all 32,896 8-mers scored against it, and `wt_id`,
    # `mut_positions` and `n_mut_from_wt` come with it. Running them per row re-answered the
    # same question 32,896 times per protein and made validation cost as much as the entire
    # parse -- the row-wise `df.apply` below was 50 s of a 139 s corpus validation on its own.
    #
    # So they run once per DISTINCT construct (~500 rows, not 16.6 million) and the row
    # counts in the messages are recovered by weighting with `_n`, the number of rows each
    # construct contributes. The reported numbers are identical, not approximate.
    axis = (
        df[["dbd_seq", "wt_id", "mut_positions", "n_mut_from_wt"]]
        .value_counts(dropna=False)
        .rename("_n")
        .reset_index()
    )
    a_dbd = axis["dbd_seq"].astype("string")

    def _rows(mask: pd.Series) -> int:
        """Rows behind a per-construct mask."""
        return int(axis.loc[mask, "_n"].sum())

    bad_aa = a_dbd.map(lambda s: bool(set(s) - AA_ALPHABET) if pd.notna(s) else False)
    if bad_aa.any():
        rep.error(
            f"dbd_seq: {_rows(bad_aa):,} rows with non-standard residues "
            f"(e.g. {_examples(a_dbd, bad_aa)})"
        )
    not_upper = a_dbd.map(lambda s: s != s.upper() if pd.notna(s) else False)
    if not_upper.any():
        rep.error(f"dbd_seq: {_rows(not_upper):,} rows are not uppercase")

    n_x = int((a_dbd.map(lambda s: s.count("X") if pd.notna(s) else 0) * axis["_n"]).sum())
    if n_x:
        rep.warn(f"dbd_seq: {n_x:,} unresolved 'X' residues across the table")

    # -- mutation bookkeeping ----------------------------------------------------------
    n_mut = axis["n_mut_from_wt"]
    if (n_mut < 0).any():
        rep.error(f"n_mut_from_wt: {_rows(n_mut < 0):,} negative values")

    def _count_positions(v: Any) -> int:
        if pd.isna(v) or str(v).strip() == "":
            return 0
        return len([p for p in str(v).split(",") if p.strip()])

    n_pos_listed = axis["mut_positions"].map(_count_positions)
    mismatch = (n_pos_listed != n_mut.fillna(-1)) & n_mut.notna()
    if mismatch.any():
        rep.error(
            f"mut_positions: {_rows(mismatch):,} rows where the position count "
            f"disagrees with n_mut_from_wt"
        )

    # `mut_positions` is in the REFERENCE's coordinate frame, not the variant's, so a
    # variant carrying a deletion can legitimately name a position past its own length. The
    # bound is the cluster's reference sequence.
    ref_len = (
        axis.loc[axis["n_mut_from_wt"] == 0]
        .drop_duplicates("wt_id")
        .set_index("wt_id")["dbd_seq"]
        .str.len()
    )

    # Clusters are assigned across the whole corpus (scripts/build_clusters.py), so a
    # cluster's representative routinely lives in a DIFFERENT source's table -- `Cell08`
    # variants under a `BAR15A` reference. A per-source validator cannot see that row, and
    # must not report its absence as an error. Such clusters are reported as a warning here
    # and checked corpus-wide where the reference is visible.
    external = sorted(set(axis.loc[axis["n_mut_from_wt"] > 0, "wt_id"]) - set(ref_len.index))

    def _positions_in_range(row: pd.Series) -> bool:
        v = row["mut_positions"]
        if pd.isna(v) or str(v).strip() == "":
            return True
        try:
            pos = [int(p) for p in str(v).split(",") if p.strip()]
        except ValueError:
            return False
        if row["wt_id"] not in ref_len.index:
            return True  # reference is in another source; bounds are unknowable here
        return all(1 <= p <= ref_len[row["wt_id"]] for p in pos)

    out_of_range = ~axis.apply(_positions_in_range, axis=1)
    if out_of_range.any():
        rep.error(
            f"mut_positions: {_rows(out_of_range):,} rows with positions outside "
            f"1..len(reference) or unparseable (1-based in the REFERENCE frame — check "
            f"isoform offsets)"
        )

    if external:
        rep.warn(
            f"wt_id: {len(external)} clusters carry variants here but their reference row is "
            f"in another source, so mut_positions cannot be bounds-checked locally "
            f"(e.g. {external[:3]}). Checked corpus-wide by scripts/build_clusters.py."
        )

    dbd_counts = df["dbd_seq"].astype("string").value_counts(dropna=False)
    uniq_dbd = pd.Series(dbd_counts.index, dtype="string")
    bad_res = uniq_dbd.map(lambda s: bool(set(s) - PROTEIN_ALPHABET) if pd.notna(s) else False)
    if bad_res.any():
        n_bad = int(dbd_counts.to_numpy()[bad_res.to_numpy(dtype=bool)].sum())
        rep.error(
            f"dbd_seq: {n_bad:,} rows with non-standard residues "
            f"(e.g. {_examples(uniq_dbd, bad_res)}) — an unresolved position is the "
            f"depositor's uncertainty, not a property of the protein; drop the construct"
        )

    # -- DNA axis ----------------------------------------------------------------------
    # Same argument as the protein axis: `dna_seq` takes only 32,896 distinct values in a
    # PBM corpus, each repeated once per construct, so the alphabet check runs on the
    # distinct sites and is weighted back to rows.
    dna_counts = df["dna_seq"].astype("string").value_counts(dropna=False)
    uniq_dna = pd.Series(dna_counts.index, dtype="string")
    bad_base = uniq_dna.map(lambda s: bool(set(s) - DNA_ALPHABET) if pd.notna(s) else False)
    if bad_base.any():
        n_bad = int(dna_counts.to_numpy()[bad_base.to_numpy(dtype=bool)].sum())
        rep.error(
            f"dna_seq: {n_bad:,} rows with non-ACGT characters "
            f"(e.g. {_examples(uniq_dna, bad_base)}) — degenerate codes and pad characters "
            f"must be resolved or dropped in the parser"
        )
    len_mismatch = df["dna_seq"].astype("string").str.len() != df["dna_len"]
    if len_mismatch.any():
        rep.error(f"dna_len: {int(len_mismatch.sum()):,} rows disagree with len(dna_seq)")
    too_long = df["dna_len"] > MAX_DNA_LEN
    if too_long.any():
        rep.error(f"dna_seq: {int(too_long.sum()):,} rows longer than {MAX_DNA_LEN} bp")

    bad_ctx = ~df["dna_context"].isin(VALID_DNA_CONTEXT)
    if bad_ctx.any():
        rep.error(f"dna_context: {int(bad_ctx.sum()):,} rows not in {sorted(VALID_DNA_CONTEXT)}")

    # -- labels and negatives ----------------------------------------------------------
    bad_label = ~df["label"].isin(VALID_LABELS)
    if bad_label.any():
        rep.error(f"label: {int(bad_label.sum()):,} rows not in {sorted(VALID_LABELS)}")

    is_neg = df["label"] == LABEL_NONBIND
    neg_prov = df["neg_provenance"]
    missing_prov = is_neg & (neg_prov.isna() | (neg_prov.astype("string").str.strip() == ""))
    if missing_prov.any():
        rep.error(
            f"neg_provenance: {int(missing_prov.sum()):,} negatives without provenance — "
            f"this is the one field that must never be blank on a label 0 row"
        )
    bad_prov = neg_prov.notna() & ~neg_prov.isin(VALID_NEG_PROVENANCE)
    if bad_prov.any():
        rep.error(
            f"neg_provenance: {int(bad_prov.sum()):,} rows with values outside "
            f"{sorted(VALID_NEG_PROVENANCE)}"
        )
    prov_on_pos = (df["label"] != LABEL_NONBIND) & neg_prov.notna()
    if prov_on_pos.any():
        rep.warn(
            f"neg_provenance: set on {int(prov_on_pos.sum()):,} non-negative rows; harmless "
            f"but usually a sign of a copied column"
        )

    # -- score sanity ------------------------------------------------------------------
    # A universal PBM E-score is a rank statistic bounded to [-0.5, 0.5]. Anything outside
    # means the wrong column was read -- median intensity and z-scores sit in the same files
    # and, in some UniPROBE accessions, in the position an E-score occupies in others.
    is_escore = df["score_type"] == "pbm_escore"
    if is_escore.any():
        out_of_range = is_escore & ((df["raw_score"] < -0.5) | (df["raw_score"] > 0.5))
        if out_of_range.any():
            bad = df.loc[out_of_range, "raw_score"]
            rep.error(
                f"raw_score: {int(out_of_range.sum()):,} pbm_escore rows outside [-0.5, 0.5] "
                f"(min {bad.min():.3g}, max {bad.max():.3g}) — the E-score column was almost "
                f"certainly misidentified"
            )

    # -- thresholds --------------------------------------------------------------------
    bad_thresh = df["threshold_pos"] < df["threshold_neg"]
    if bad_thresh.any():
        rep.error(f"thresholds: {int(bad_thresh.sum()):,} rows with threshold_pos < threshold_neg")

    # -- identity ----------------------------------------------------------------------
    recomputed = add_pair_ids(df)["pair_id"]
    wrong_id = recomputed != df["pair_id"]
    if wrong_id.any():
        rep.error(
            f"pair_id: {int(wrong_id.sum()):,} rows whose hash does not match "
            f"{PAIR_ID_KEYS}; regenerate with schema.add_pair_ids()"
        )
    dup = df["pair_id"].duplicated()
    if dup.any():
        rep.error(
            f"pair_id: {int(dup.sum()):,} duplicate rows — the same (DBD, DNA, assay, "
            f"stringency) measured twice needs collapsing or a stringency distinction"
        )

    # -- cluster structure -------------------------------------------------------------
    if strict_wt:
        has_wt = axis.groupby("wt_id")["n_mut_from_wt"].min() == 0
        orphan = [c for c in has_wt[~has_wt].index.tolist() if c not in external]
        if orphan:
            rep.warn(
                f"wt_id: {len(orphan)} clusters with no n_mut_from_wt == 0 reference row "
                f"(e.g. {orphan[:3]}) — fine if the WT was not assayed, but check"
            )
        lens = axis.assign(_l=a_dbd.str.len()).groupby("wt_id")["_l"].nunique()
        ragged = lens[lens > 1]
        if len(ragged):
            rep.warn(
                f"wt_id: {len(ragged)} clusters contain DBDs of differing length "
                f"(e.g. {list(ragged.index[:3])}). Allowed since distance is alignment-based; "
                f"check they are real indels and not padding clipped by a short construct"
            )

    # -- summary stats -----------------------------------------------------------------
    counts = df["label"].value_counts()
    n_pos = int(counts.get(LABEL_BIND, 0))
    n_neg = int(counts.get(LABEL_NONBIND, 0))
    rep.stats = {
        "n_rows": len(df),
        "n_pos": n_pos,
        "n_neg": n_neg,
        "n_gray": int(counts.get(LABEL_GRAY, 0)),
        "pos_rate": round(n_pos / len(df), 6),
        "neg_per_pos": round(n_neg / n_pos, 2) if n_pos else None,
        "n_clusters": int(df["wt_id"].nunique()),
        "n_dbd": int(df["dbd_seq"].nunique()),
        "n_dna": int(df["dna_seq"].nunique()),
        "dna_len": sorted(df["dna_len"].dropna().unique().tolist()),
        "families": df["dbd_family"].value_counts().to_dict(),
        "neg_provenance": df.loc[is_neg, "neg_provenance"].value_counts().to_dict(),
    }
    return rep


__all__ = [
    "COLUMNS",
    "COLUMN_NAMES",
    "DERIVED",
    "DTYPES",
    "LABEL_BIND",
    "LABEL_GRAY",
    "LABEL_NONBIND",
    "MAX_DNA_LEN",
    "PAIR_ID_KEYS",
    "SchemaValidationError",
    "ValidationReport",
    "add_pair_ids",
    "coerce",
    "empty_frame",
    "make_pair_id",
    "validate",
]
