#!/usr/bin/env python
"""Generate the list of DNA-binding Pfam families used by the admission policy.

    python scripts/build_dbd_family_list.py

UniPROBE publishes a `Domain` label for every experiment on its browse page. Those labels
are the database's own curation of what does the DNA binding, so they are the right basis
for the whitelist — but they are free text ("Zinc Finger C2H2", "HMG BOX", "forkhead"), so
each token is resolved against Pfam-A's own `NAME` fields rather than trusted verbatim.

Tokens that resolve to nothing are printed, not silently dropped.
"""

from __future__ import annotations

import re

from snp2prot.config import EXTERNAL_DIR, PROJECT_ROOT

BROWSE = EXTERNAL_DIR / "uniprobe" / "browse.html"
PFAM = EXTERNAL_DIR / "pfam" / "Pfam-A.hmm"
OUT = EXTERNAL_DIR / "pfam" / "dbd_families.txt"

#: Labels that name a fold or a concept rather than a Pfam family, mapped by hand. Each is a
#: judgement call and is listed explicitly so it can be audited.
MANUAL = {
    # UniPROBE labels predate several Pfam renames. Each was resolved by looking the Pfam
    # ACCESSION up in Pfam-A and reading its current NAME, not by guessing at the string.
    "homeobox": "Homeodomain",  # PF00046
    "fork_head": "Forkhead",  # PF00250
    "zn2cys6": "Zn_clus",  # PF00172
    "mads": "SRF-TF",  # PF00319
    "myb": "Myb_DNA-binding",  # PF00249
    "rfx": "RFX_DNA_binding",  # PF02257
    "e2f_tdp": "WHD_E2F_TDP",  # PF02319
    "nr": "zf-C4",  # PF00105
    "bright": "ARID",  # PF01388
    "ap-2": "TF_AP-2",  # PF03299 (mammalian TFAP2; plant "AP2" is separate)
    "pbx": "PBC",
    "zinc finger c2h2": "zf-C2H2",
    "c2h2 znf": "zf-C2H2",
    "gata type znf": "GATA",
    "zf-nhr/gata-type": "GATA",
    "hmg box": "HMG_box",
    "myb/sant-like": "Myb_DNA-binding",
    "sant": "Myb_DNA-binding",
    "tbox": "T-box",
    "znf_c4": "zf-C4",
    "nr_c4": "zf-C4",
    "bhlh": "HLH",
    "myc-type": "HLH",
    "basic": "HLH",
    "bzip": "bZIP_1",
    "brlz": "bZIP_1",
    "wh": "Forkhead",
    "hth apses-type": "KilA-N",
}
#: Labels that are not DNA-binding domains at all, or are too vague to resolve.
IGNORE = {
    "",
    "distant similarity to homeodomain",
    "hth",
    "dwa",
    "nr lbd",
    "tig",
    "sam_pnt",
    "lim",
    "pwwp",
    "mtf2_c",
    "stb3",
    "vhr1",
    "gcr1_c",
    "ste",
}


def pfam_names() -> set[str]:
    if not PFAM.exists():
        raise SystemExit(f"Pfam-A not found: {PFAM}")
    return {
        line.split(None, 1)[1].strip()
        for line in PFAM.read_text(errors="ignore").splitlines()
        if line.startswith("NAME")
    }


def main() -> None:
    if not BROWSE.exists():
        raise SystemExit(f"browse page not cached: {BROWSE}")
    html = BROWSE.read_text(errors="ignore")
    rows = re.findall(r'value="[^"/]+/[^"/]+/[^"]*".*?</a></td>\s*<td>([^<]*)</td>', html, re.S)

    names = pfam_names()
    lower = {n.lower(): n for n in names}
    resolved, unresolved = {}, set()
    for label in rows:
        for token in (t.strip() for t in label.split(",")):
            key = token.lower()
            if key in IGNORE:
                continue
            if key in MANUAL:
                resolved.setdefault(MANUAL[key], set()).add(token)
            elif key in lower:
                resolved.setdefault(lower[key], set()).add(token)
            else:
                unresolved.add(token)

    missing = sorted(f for f in resolved if f not in names)
    lines = [
        "# DNA-binding Pfam families used by the domain admission policy.",
        "# Generated by scripts/build_dbd_family_list.py from UniPROBE's own Domain labels,",
        "# resolved against Pfam-A NAME fields. Do not hand-edit; re-run the script.",
        "",
    ]
    lines += sorted(resolved)
    OUT.write_text("\n".join(lines) + "\n")

    print(f"{len(resolved)} DNA-binding families -> {OUT.relative_to(PROJECT_ROOT)}")
    if missing:
        print(f"WARNING: {len(missing)} mapped names absent from Pfam-A: {missing}")
    if unresolved:
        print(f"unresolved labels ({len(unresolved)}), not included: {sorted(unresolved)}")


if __name__ == "__main__":
    main()
