#!/usr/bin/env python
"""Build the label-health side table and its report.

    python scripts/build_label_health.py [--out-report reports/label_health.md] [--dry-run]

One row per `(dbd_seq, source_dataset)` record: label counts, best E-score, and a verdict
saying whether the record carries positive evidence, is a variant that measurably lost
binding, or is silent with nothing to compare it against. What the verdicts mean is
`snp2prot.label_health`; why the table exists rather than a changed cutoff is `T20`/`T21` in
`docs/DECISIONS.md`.

**This reads the corpus and writes nothing else.** No label, threshold or parsed table is
touched. Sources are streamed in batches because the corpus is 45 million rows and the only
columns needed are five of twenty-two.
"""

from __future__ import annotations

import argparse
import time
from pathlib import Path

import pandas as pd
import pyarrow.parquet as pq

from snp2prot import label_health, thresholds
from snp2prot.config import LABEL_HEALTH_TABLE, REPORTS_DIR, source_tables

COLUMNS = ["dbd_seq", "source_dataset", "protein_id", "wt_id", "dbd_family", "label", "raw_score"]
BATCH_ROWS = 2_000_000


def scan_source(path: Path) -> pd.DataFrame:
    """Per-record statistics for one source, one batch at a time."""
    parts = []
    for batch in pq.ParquetFile(path).iter_batches(batch_size=BATCH_ROWS, columns=COLUMNS):
        parts.append(label_health.summarise(batch.to_pandas()))
    combined = pd.concat(parts, ignore_index=True)
    # A record can straddle batches, so fold the partial summaries together.
    keys = ["dbd_seq", "source_dataset"]
    return (
        combined.groupby(keys, sort=False)
        .agg(
            protein_id=("protein_id", "first"),
            wt_id=("wt_id", "first"),
            dbd_family=("dbd_family", "first"),
            n_rows=("n_rows", "sum"),
            max_escore=("max_escore", "max"),
            n_at_cutoff=("n_at_cutoff", "sum"),
            n_pos=("n_pos", "sum"),
            n_neg=("n_neg", "sum"),
            n_gray=("n_gray", "sum"),
        )
        .reset_index()
    )


def write_report(records: pd.DataFrame, per_source: pd.DataFrame, path: Path, cutoff: float):
    counts = records.verdict.value_counts()
    n_dead = int(counts.get(label_health.DEAD_VARIANT, 0))
    n_none = int(counts.get(label_health.NO_EVIDENCE, 0))
    silent = records[records.verdict != label_health.OK]
    lost_rows = int(records.loc[records.verdict == label_health.NO_EVIDENCE, "n_rows"].sum())

    lines = [
        "# Label health — which records carry positive evidence",
        "",
        f"Generated by `scripts/build_label_health.py`. Cutoff `E >= {cutoff}`, unchanged:",
        "`T20` closed 2026-08-18 in favour of keeping it (`docs/DECISIONS.md`).",
        "",
        "**No label was changed to produce this.** The table records what the corpus already",
        "says, so that a silent record can be filtered at training time instead of being",
        "mistaken for measured non-binding. Read it with `snp2prot.label_health.load`, or",
        "filter a frame with `label_health.usable(df)`.",
        "",
        "## The three verdicts",
        "",
        "| verdict | meaning | records |",
        "|---|---|---:|",
        f"| `ok` | at least one 8-mer at or above the cutoff "
        f"| {int(counts.get(label_health.OK, 0)):,} |",
        "| `dead_variant` | no positives, but another record of the same cluster **and source** "
        f"has them — its own series is the control | {n_dead:,} |",
        "| `no_evidence` | no positives and no such control: indistinguishable from an "
        f"experiment too weak to see anything | {n_none:,} |",
        "",
        f"`no_evidence` covers **{lost_rows:,} rows** ({lost_rows / int(records.n_rows.sum()):.1%} "
        "of the corpus), which is what `label_health.usable` drops.",
        "",
        "## By source",
        "",
        "No record's verdict depends on these columns — that turns on whether the record has",
        "a control in its own cluster and source. They are context. `frac_silent` is the one",
        "to read: a source that sees normally has almost none, and `median max E` is only a",
        "supporting figure because a source full of dead variants drags its own median down.",
        "",
        "| source | records | silent | median max E | positive rate | `dead_variant` | "
        "`no_evidence` |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for r in per_source.itertuples():
        blind = r.median_max_escore < cutoff
        name = f"**`{r.source_dataset}`**" if blind else f"`{r.source_dataset}`"
        median = f"**{r.median_max_escore:.3f}**" if blind else f"{r.median_max_escore:.3f}"
        lines.append(
            f"| {name} | {r.n_records:,} | {r.frac_silent:.0%} | {median} | "
            f"{r.positive_rate:.4%} | {getattr(r, f'n_{label_health.DEAD_VARIANT}'):,} | "
            f"{getattr(r, f'n_{label_health.NO_EVIDENCE}'):,} |"
        )

    blocked = silent[silent.n_at_cutoff > 0]
    lines += [
        "",
        f"## {len(blocked)} of the silent records are not weak — their replicates disagreed",
        "",
        f"{len(blocked)} records reach the cutoff on their stored score and still have no",
        "positive, because labels are binarized per experiment and replicates that disagree",
        "become `LABEL_GRAY`. They are borderline binders measured twice with different",
        "answers, not blind experiments, and they are why `n_at_cutoff` sits beside `n_pos`.",
        "",
        "## Every silent record",
        "",
        "| domain | source | cluster | family | max E | 8-mers at cutoff | gray | verdict |",
        "|---|---|---|---|---:|---:|---:|---|",
    ]
    for r in silent.sort_values(["verdict", "source_dataset", "gene"]).itertuples():
        lines.append(
            f"| `{r.gene}` | `{r.source_dataset}` | `{r.wt_id}` | {r.dbd_family} | "
            f"{r.max_escore:.3f} | {r.n_at_cutoff} | {r.n_gray:,} | `{r.verdict}` |"
        )
    lines.append("")
    path.write_text("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-report", type=Path, default=REPORTS_DIR / "label_health.md")
    ap.add_argument("--dry-run", action="store_true", help="print the summary, write nothing")
    args = ap.parse_args()

    cutoff = float(thresholds.for_assay("pbm")["positive"])
    started = time.time()
    frames = []
    for source, path in source_tables().items():
        t0 = time.time()
        frames.append(scan_source(path))
        print(f"  {source:<16} {len(frames[-1]):>5} records  {time.time() - t0:5.1f}s")

    records = label_health.with_gene_names(
        label_health.classify(pd.concat(frames, ignore_index=True))
    )
    per_source = label_health.source_summary(records)

    counts = records.verdict.value_counts()
    print(f"\n{len(records):,} records in {time.time() - started:.0f}s")
    for verdict in (label_health.OK, label_health.DEAD_VARIANT, label_health.NO_EVIDENCE):
        print(f"  {verdict:<14} {int(counts.get(verdict, 0)):>6}")
    weak = per_source[per_source.median_max_escore < cutoff]
    if not weak.empty:
        print(f"\nsources whose median domain never reaches E >= {cutoff}:")
        for r in weak.itertuples():
            print(f"  {r.source_dataset:<16} median max E {r.median_max_escore:.3f}")

    if args.dry_run:
        return
    LABEL_HEALTH_TABLE.parent.mkdir(parents=True, exist_ok=True)
    records.to_parquet(LABEL_HEALTH_TABLE, index=False)
    write_report(records, per_source, args.out_report, cutoff)
    print(f"\nwrote {LABEL_HEALTH_TABLE}\nwrote {args.out_report}")


if __name__ == "__main__":
    main()
