#!/usr/bin/env python
"""Decide which benchmark TFs enter the GHT arm, and store the domain each one stands for.

    python scripts/build_ght_panel.py            # ~40 s, one Pfam-A scan over 139 constructs

Phase A of `docs/GHT_PLAN.md` §11. Reads the benchmark's own TF list and the Codebook metadata,
picks one construct per TF, and runs it through `snp2prot.domains` — **the same admission path
every other source uses**, which is what §11 asks for and what the plan's own family-label count
of 47 did not do.

Writes `data/interim/ght/panel.parquet` and `rejected.parquet`, and
`reports/ght_panel.md` beside them.
"""

from __future__ import annotations

import argparse

import pandas as pd

from snp2prot import tracking
from snp2prot.ght import config, panel


def report(admitted: pd.DataFrame, rejected: pd.DataFrame) -> str:
    total = len(admitted) + len(rejected)
    lines = [
        "# The GHT-SELEX panel",
        "",
        "Generated by `scripts/build_ght_panel.py`. The benchmark ships 139 TFs "
        "(`TFs_CHS+AFS.txt`); this is what the admission policy makes of them.",
        "",
        "**The panel is decided by `snp2prot.domains`, not by the `DBD(s)` label** "
        "(`docs/GHT_PLAN.md` §11). The plan's own §4 counted 47 usable TFs by subtracting the 92 "
        "labelled `C2H2 ZF` from 139. That is a count of what the curators believe each protein "
        "contains; the policy counts what a Pfam scan finds and whether the found region is "
        "solely responsible, contiguous and resolvable. The two disagree, and this table is the "
        "disagreement.",
        "",
        "| | count |",
        "|---|---:|",
        f"| benchmark TFs | {total} |",
        f"| admitted | **{len(admitted)}** |",
        f"| rejected | {len(rejected)} |",
        "",
        "## Why the others did not enter",
        "",
        "| reason | count | what it means |",
        "|---|---:|---|",
    ]
    silent = rejected[rejected.rejection == "no_domain"]
    no_domain = len(silent)
    with_hits = int((silent.other_hits.astype(str).str.len() > 0).sum())
    meanings = {
        "repeat_array": "more than one Pfam hit of one family — a zinc-finger array, condition 2",
        "c2h2_array_d10": "one `zf-C2H2` hit where the curators count 2-25 fingers (`D10`)",
        "no_domain": "no Pfam hit in any family on `dbd_families.txt`",
        "mixed_families": "two DNA-binding families in one construct — condition 1",
        "unresolved_residue": "a non-standard residue inside the padded window",
    }
    for reason, count in rejected.rejection.value_counts().items():
        lines.append(f"| `{reason}` | {count} | {meanings.get(reason, '')} |")
    lines += [
        "",
        "### The `no_domain` rejections are mostly a family-list gap, not an absent domain",
        "",
        f"{with_hits} of the {no_domain} have Pfam hits and none of those hits is on "
        "`data/external/pfam/dbd_families.txt`, which was generated from UniPROBE's and CIS-BP's "
        "own curation and therefore covers the families **those** corpora contain. The human "
        "Codebook panel reaches families they do not. The remaining "
        f"{no_domain - with_hits} have no Pfam hit anywhere in the construct at all, above the "
        "gathering threshold, and are a genuine absence rather than a coverage gap.",
        "",
        "| TF | declared DBD | Pfam hits found (none admitted) |",
        "|---|---|---|",
    ]
    for r in rejected[rejected.rejection == "no_domain"].itertuples():
        lines.append(f"| `{r.tf}` | {r.declared_dbd} | {r.other_hits or '—'} |")
    lines += [
        "",
        "One of them, `MKX`, is a latent defect rather than a coverage gap: its only hit is "
        "`Homeobox_KN`, which `snp2prot.domains.FAMILY_ALIASES` already maps to `Homeodomain` — "
        "but `call_domain` filters on the family list **before** applying the alias, so an alias "
        "only ever fires for a family that is already admitted. Flagged, not fixed: the family "
        "list is shared with the PBM corpus and editing it re-decides 1,338 domains.",
        "",
        "## Admitted",
        "",
        "| TF | family | DBD aa | construct | construct aa | declared |",
        "|---|---|---:|---|---:|---|",
    ]
    for r in admitted.sort_values(["dbd_family", "tf"]).itertuples():
        lines.append(
            f"| `{r.tf}` | {r.dbd_family} | {len(r.dbd_seq)} | {r.insert_composition} "
            f"| {r.construct_len} | {r.declared_dbd} |"
        )
    families = admitted.dbd_family.value_counts()
    lines += [
        "",
        f"{len(families)} families over {len(admitted)} TFs; "
        f"largest is `{families.index[0]}` at {families.iloc[0]}.",
        "",
        "## What this costs",
        "",
        f"Setting 2 of `GHT_PLAN.md` §9 — held-out TF — now has **{len(admitted)}** proteins "
        "where the plan budgeted 47, and the plan already called 47 thin. Per-fold variance is "
        "reported rather than a single mean, and the ten clean extras of §4 are the cheapest "
        "widening if it is wanted.",
        "",
        tracking.provenance_line(),
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--keep-c2h2", action="store_true", help="ignore D10, admit single-finger hits")
    args = ap.parse_args()

    admitted, rejected = panel.build(drop_c2h2=not args.keep_c2h2)
    admitted = admitted.sort_values("tf").reset_index(drop=True)
    config.GHT_INTERIM.mkdir(parents=True, exist_ok=True)
    admitted.to_parquet(config.PANEL_TABLE, index=False)
    rejected.to_parquet(config.REJECTED_TABLE, index=False)

    path = config.REPORT_DIR / "ght_panel.md"
    path.write_text(report(admitted, rejected))
    print(f"{len(admitted)} admitted, {len(rejected)} rejected")
    print(rejected.rejection.value_counts().to_string())
    print(f"wrote {config.PANEL_TABLE}")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
