#!/usr/bin/env python
"""Cut every benchmark window out of hg38 and cache it as base tokens.

    python scripts/build_ght_windows.py            # ~8 min, one pass over hg38

Phase A of `docs/GHT_PLAN.md` §11. Reads the MEX-ArChIPelago BEDs straight out of
`datasets.zip` — positives, `shades`, and a seeded 10:1 subsample of `random` and `aliens` —
and writes one `.npz` per TF under `data/interim/ght/windows/`.

hg38 is a plain gzip with no index, so the genome is decompressed **once** and each chromosome
is served while it is resident. Nothing here writes to `data/raw/`.
"""

from __future__ import annotations

import argparse
import time

import pandas as pd

from snp2prot import tracking
from snp2prot.ght import config, panel, windows


def report(summary: pd.DataFrame, split: pd.DataFrame, ratio: int) -> str:
    wide = summary.pivot_table(index="tf", columns=["split", "set"], values="n", fill_value=0)
    totals = summary.groupby(["split", "set"]).n.sum()
    lines = [
        "# GHT-SELEX windows",
        "",
        "Generated by `scripts/build_ght_windows.py` from the MEX-ArChIPelago release "
        "(`10.5281/zenodo.15555251`) and hg38. Positives are the benchmark's own 301 bp "
        "summit-centred peaks; the negative sets and the chromosome split are theirs unchanged "
        "(`docs/GHT_PLAN.md` D3-D5).",
        "",
        "## What was cut",
        "",
        "| split | set | windows |",
        "|---|---|---:|",
    ]
    for (s, name), n in totals.items():
        lines.append(f"| {s} | `{name}` | {n:,} |")
    dropped = int(summary.n_dropped.sum())
    lines += [
        "",
        f"{dropped:,} windows were dropped for carrying a base outside `ACGT`"
        + (
            " — none, which is what the benchmark's own `N` exclusion promises."
            if dropped == 0
            else f" ({100 * dropped / max(int(summary.n.sum()) + dropped, 1):.4f}% of the total). "
            "The release's `N` exclusion says this should not happen; the count is small enough "
            "to be assembly gaps at contig edges and is reported rather than repaired. The "
            "per-(TF, split, set) counts are in `data/interim/ght/window_summary.parquet`, "
            "column `n_dropped`."
        ),
        "",
        f"**`random` and `aliens` are subsampled to {ratio}:1**, seeded, because the released "
        "sets are 100:1 and 40 million windows is 12 GB of tokens for a control that is read on "
        "auROC. auROC is invariant to the imbalance; **auPRC on those two sets is therefore not "
        "comparable to the published 100:1 numbers** and is reported against its own chance "
        "level like every other per-protein AUPR in this project.",
        "",
        "## The chromosome split is a partition",
        "",
        "| side | chromosomes | which |",
        "|---|---:|---|",
    ]
    for r in split.itertuples():
        lines.append(f"| {r.split} | {r.n_chromosomes} | {r.chromosomes or '—'} |")
    lines += [
        "",
        "A chromosome on both sides would let a locus straddle the split; there is none.",
        "",
        "## Per TF",
        "",
        "| TF | train pos | train shades | test pos | test shades | test random | test aliens |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for tf in wide.index:
        row = wide.loc[tf]
        lines.append(
            f"| `{tf}` | {row[('Train', 'positives')]:,} | {row[('Train', 'shades')]:,} "
            f"| {row[('Test', 'positives')]:,} | {row[('Test', 'shades')]:,} "
            f"| {row[('Test', 'random')]:,} | {row[('Test', 'aliens')]:,} |"
        )
    lines += ["", tracking.provenance_line()]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ratio", type=int, default=windows.NEGATIVE_RATIO)
    ap.add_argument("--tf", action="append", help="build only these TFs (repeatable)")
    args = ap.parse_args()

    tfs = args.tf or list(panel.load().tf)
    print(f"{len(tfs)} TFs; planning windows from {config.DATASETS_ZIP.name}", flush=True)
    started = time.time()

    def progress(chrom: str, cut: int, missed: int) -> None:
        note = f"  {chrom}: {cut:,} cut" + (f", {missed:,} off-contig" if missed else "")
        print(f"{note}   ({time.time() - started:.0f}s)", flush=True)

    built, summary = windows.build(tfs, ratio=args.ratio, progress=progress)
    for w in built:
        w.save()
    split = windows.chromosome_split(built)

    config.GHT_INTERIM.mkdir(parents=True, exist_ok=True)
    summary.to_parquet(config.GHT_INTERIM / "window_summary.parquet", index=False)
    path = config.REPORT_DIR / "ght_windows.md"
    path.write_text(report(summary, split, args.ratio))

    total = int(summary.n.sum())
    print(f"{total:,} windows over {len(built)} TFs in {time.time() - started:.0f}s")
    print(f"wrote {config.WINDOW_DIR}")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
