#!/usr/bin/env python
"""How much of the panel binds the same loci — which is what says what `aliens` measures.

    python scripts/check_ght_cobinding.py            # ~2 min, CPU only

Two numbers per TF, both read off the benchmark's own test-chromosome peaks:

1. **What fraction of this TF's `aliens` windows are a peak of another TF *in our panel*.**
   `aliens` is "regions sampled from peaks of other TFs" across the whole Codebook set, so a
   priori most of them belong to proteins the model has never seen. The fraction that belong to
   a *training* TF is the part where the model has been told, in training, that this window is
   bound — by someone else. Those windows cannot be answered by "does this look like a peak";
   only the protein can separate them.

2. **What fraction of this TF's own positives another panel TF also binds.** This is the
   *upper bound on the protein-blind shortcut*: co-bound promoters and enhancers are exactly the
   windows a model with no protein input can get right, because the answer is the same for
   several proteins at once.

Writes `data/processed/ght/ght_cobinding.parquet` and `reports/ght_cobinding.md`.
"""

from __future__ import annotations

import argparse
import time
from collections import defaultdict

import numpy as np
import pandas as pd

from snp2prot import tracking
from snp2prot.ght import config, panel, windows


def overlaps(chroms: np.ndarray, starts: np.ndarray, peaks: dict[str, np.ndarray]) -> np.ndarray:
    """Which of `(chroms, starts)` fall within one window width of a peak in `peaks`.

    Both sides are fixed-width windows on the same grid, so "overlapping" is `|s - p| < WINDOW`
    and a binary search over one sorted array per chromosome answers it — an interval tree for a
    fixed width would be the same computation with more machinery.
    """
    hit = np.zeros(len(starts), dtype=bool)
    for chrom in np.unique(chroms):
        rows = chroms == chrom
        reference = peaks.get(str(chrom))
        if reference is None or not len(reference):
            continue
        position = starts[rows]
        index = np.searchsorted(reference, position)
        near = np.zeros(len(position), dtype=bool)
        # The nearest peak on either side; a fixed width means no third candidate can be closer.
        for offset in (-1, 0):
            clipped = np.clip(index + offset, 0, len(reference) - 1)
            near |= np.abs(reference[clipped] - position) < windows.WINDOW
        hit[rows] = near
    return hit


def report(frame: pd.DataFrame) -> str:
    lines = [
        "# How much of the GHT panel binds the same loci",
        "",
        "Generated by `scripts/check_ght_cobinding.py`, over the benchmark's **test**-chromosome "
        "peaks only. It exists to say what the `aliens` negative set actually asks, and what the "
        "ceiling on a protein-blind shortcut is.",
        "",
        "| | median | min | max |",
        "|---|---:|---:|---:|",
        f"| alien windows that are a **panel** TF's peak | "
        f"{frame.alien_is_panel_peak.median():.3f} | {frame.alien_is_panel_peak.min():.3f} "
        f"| {frame.alien_is_panel_peak.max():.3f} |",
        f"| own positives another **panel** TF also binds | "
        f"{frame.pos_also_another_panel_tf.median():.3f} "
        f"| {frame.pos_also_another_panel_tf.min():.3f} "
        f"| {frame.pos_also_another_panel_tf.max():.3f} |",
        "",
        "**Half of every TF's alien negatives are a peak of a TF the model trained on.** The "
        "model was shown those exact loci as positives — for a different protein. A model that "
        "answers *does this window look bound* has to get them wrong; only a model that "
        "conditions on the protein can get them right. That makes `aliens` the sharpest control "
        "in the set, and the one a per-TF baseline is not even asked.",
        "",
        "**And a median 38% of a TF's own positives are bound by another panel TF too.** That is "
        "the size of the protein-blind shortcut on the positive side: co-bound promoters and "
        "enhancers where the answer is the same for several proteins at once. It is why "
        "`protein = constant` is not a strawman control but a genuinely strong model, and why a "
        "Setting 1 auPRC means little until it is read against it.",
        "",
        "| TF | alien windows | that are a panel peak | positives | co-bound |",
        "|---|---:|---:|---:|---:|",
    ]
    for r in frame.sort_values("pos_also_another_panel_tf", ascending=False).itertuples():
        lines.append(
            f"| `{r.tf}` | {r.n_alien:,} | {r.alien_is_panel_peak:.3f} | {r.n_pos:,} "
            f"| {r.pos_also_another_panel_tf:.3f} |"
        )
    lines += ["", tracking.provenance_line()]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--split", default="Test", choices=list(windows.SPLITS))
    args = ap.parse_args()

    table = panel.load()
    started = time.time()
    peaks: dict[str, dict[str, np.ndarray]] = defaultdict(dict)
    aliens: dict[str, tuple[np.ndarray, np.ndarray]] = {}
    for tf in table.tf:
        w = windows.TFWindows.load(tf)
        positive = (w.label == 1) & (w.split == args.split)
        for chrom in np.unique(w.chrom[positive]):
            peaks[tf][str(chrom)] = np.sort(w.start[positive & (w.chrom == chrom)])
        alien = (w.negset == "aliens") & (w.split == args.split)
        aliens[tf] = (w.chrom[alien], w.start[alien])
    print(f"loaded {len(table)} TFs ({time.time() - started:.0f}s)", flush=True)

    rows = []
    for tf in table.tf:
        chroms, starts = aliens[tf]
        alien_hit = np.zeros(len(starts), dtype=bool)
        own_chroms = np.concatenate([np.full(len(v), c) for c, v in peaks[tf].items()])
        own_starts = np.concatenate(list(peaks[tf].values()))
        co_bound = np.zeros(len(own_starts), dtype=bool)
        for other in table.tf:
            if other == tf:
                continue
            alien_hit |= overlaps(chroms, starts, peaks[other])
            co_bound |= overlaps(own_chroms, own_starts, peaks[other])
        rows.append(
            {
                "tf": tf,
                "n_alien": len(starts),
                "alien_is_panel_peak": float(alien_hit.mean()),
                "n_pos": len(own_starts),
                "pos_also_another_panel_tf": float(co_bound.mean()),
            }
        )
        print(f"  {tf} ({time.time() - started:.0f}s)", flush=True)

    frame = pd.DataFrame(rows)
    config.GHT_PROCESSED.mkdir(parents=True, exist_ok=True)
    frame.to_parquet(config.GHT_PROCESSED / "ght_cobinding.parquet", index=False)
    path = config.REPORT_DIR / "ght_cobinding.md"
    path.write_text(report(frame))
    print(
        f"\nmedian alien-is-a-panel-peak {frame.alien_is_panel_peak.median():.3f}; "
        f"median co-bound positives {frame.pos_also_another_panel_tf.median():.3f}"
    )
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
