#!/usr/bin/env python
"""Are the learned convolution filters motifs? Compare them to the benchmark's own PWMs.

    python scripts/check_ght_filters.py [--checkpoint ...]        # ~20 s, CPU only

`GHT_PLAN.md` §5 argues that the genomic DNA encoder is *the learned generalisation of the PWM
baseline*: a PWM best-hit score is one fixed filter followed by a global maximum, and this
encoder is 256 learned filters at four widths followed by the same maximum over both strands.
That is an argument about form. This script asks whether it is also true about content.

**A `Conv1d` weight over a one-hot encoding is a position weight matrix.** `weight[c, b, j]` is
what base `b` at offset `j` contributes to channel `c`, which is exactly what a log-odds column
is — up to an additive constant per column, because a one-hot column always sums to one, so
adding a constant to a column changes every window's score by the same amount and cannot change
a ranking. Centring each column removes that freedom and makes the two objects comparable.

Similarity is then Pearson correlation over the aligned columns, maximised over every offset and
both strands, with a minimum overlap so a one-column "match" cannot score 1.0. That is the
ungapped core of what TOMTOM does, implemented here rather than adding a MEME-suite dependency
for thirty lines.

Writes `reports/ght_filters.md`.
"""

from __future__ import annotations

import argparse

import numpy as np
import pandas as pd

from snp2prot import tracking
from snp2prot.ght import baselines, config, panel
from snp2prot.ght.baselines import MIN_OVERLAP, learned_filters, motif_similarity


def shuffled(banks: dict[int, np.ndarray], seed: int = 20260915) -> dict[int, np.ndarray]:
    """The same filters with each one's columns permuted — the null this comparison needs.

    A best-of-256 maximum is biased upward whatever the filters contain, so "median best
    similarity 0.89" means nothing without the number the same search returns on filters that
    cannot be motifs. Permuting the positions *within* a filter keeps every column and therefore
    the whole weight distribution, and destroys only the order — which is exactly what a motif is.
    """
    rng = np.random.default_rng(seed)
    out = {}
    for width, block in banks.items():
        copy = block.copy()
        for channel in range(copy.shape[0]):
            copy[channel] = copy[channel][rng.permutation(copy.shape[1])]
        out[width] = copy
    return out


def best_against(banks: dict[int, np.ndarray], pwms: dict) -> pd.DataFrame:
    """Best similarity to each TF's motif over every filter in the bank."""
    rows = []
    for width, block in sorted(banks.items()):
        for channel in range(block.shape[0]):
            for tf, pwm in pwms.items():
                rows.append(
                    {
                        "filter_width": width,
                        "channel": channel,
                        "tf": tf,
                        "pwm": pwm.name,
                        "pwm_width": pwm.width,
                        "similarity": motif_similarity(block[channel], pwm.matrix),
                    }
                )
    return pd.DataFrame(rows)


def report(matches: pd.DataFrame, best_per_tf: pd.DataFrame, meta: dict) -> str:
    lines = [
        "# Are the learned filters motifs?",
        "",
        "Generated by `scripts/check_ght_filters.py` from "
        f"`{meta['checkpoint']}`. A `Conv1d` weight over a one-hot encoding **is** a position "
        "weight matrix, up to an additive constant per column that no ranking can see; centring "
        "the columns removes that freedom and makes the two comparable. Similarity is Pearson "
        "correlation over the aligned columns, maximised over offsets and both strands, with at "
        f"least {MIN_OVERLAP} columns overlapping.",
        "",
        f"{meta['n_filters']} learned filters at widths {meta['widths']}, against the "
        f"{meta['n_pwms']} motifs the PWM baseline selected — one per panel TF, each chosen on "
        "that TF's own training chromosomes.",
        "",
        "## Every panel TF's motif is recognisable in the filter bank",
        "",
        "| TF | selected motif width | best learned filter | similarity |",
        "|---|---:|---|---:|",
    ]
    for r in best_per_tf.sort_values("similarity", ascending=False).itertuples():
        lines.append(
            f"| `{r.tf}` | {r.pwm_width} | w{r.filter_width}#{r.channel} | {r.similarity:.3f} |"
        )
    lines += [
        "",
        f"Median best similarity **{best_per_tf.similarity.median():.3f}**, range "
        f"{best_per_tf.similarity.min():.3f}–{best_per_tf.similarity.max():.3f}.",
        "",
        "**Against its null.** A best-of-256 maximum is biased upward whatever the filters "
        "contain, so the same search was run over the same filters with each one's *columns "
        "permuted* — same weights, same distribution, no order, and order is what a motif is. "
        f"The permuted bank's median best match is **{meta['null_median']:.3f}**, range "
        f"{meta['null_min']:.3f}–{meta['null_max']:.3f}. "
        f"{meta['n_above_null']} of {meta['n_pwms']} TFs beat their own permuted best.",
        "",
        "## Which widths carry the matches",
        "",
        "| filter width | TFs whose best match sits here |",
        "|---:|---:|",
    ]
    counts = best_per_tf.filter_width.value_counts().sort_index()
    for width, count in counts.items():
        lines.append(f"| {width} | {count} |")
    lines += [
        "",
        "This is the `GHT_PLAN.md` §5 decision measured rather than argued: several widths were "
        "used because real DBD motifs run roughly 6-20 bp and a single-layer convolution followed "
        "by a global maximum has no composition across layers, so one width caps what a filter "
        "can express. If every match landed at one width the bank would be wasted.",
        "",
        "## How much of the bank is motif-like at all",
        "",
        "| best similarity to **any** selected motif | filters |",
        "|---|---:|",
    ]
    bins = [(0.8, 1.01), (0.6, 0.8), (0.4, 0.6), (-1.01, 0.4)]
    per_filter = matches.groupby(["filter_width", "channel"]).similarity.max()
    for lo, hi in bins:
        n = int(((per_filter >= lo) & (per_filter < hi)).sum())
        label = f"{lo:.1f} – {min(hi, 1.0):.1f}" if lo > -1 else f"below {hi:.1f}"
        lines.append(f"| {label} | {n} |")
    lines += [
        "",
        "A filter with no close match is not a failure. The bank is trained on 33 proteins at "
        "once and has 256 channels; some of them will be encoding composition, flank structure, "
        "or a motif no panel TF's selected PWM happens to describe.",
        "",
        tracking.provenance_line(),
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--checkpoint", default=None, help="default: the C1/all run at the base seed")
    ap.add_argument("--which", default="best", choices=["best", "final"])
    args = ap.parse_args()

    checkpoint = args.checkpoint
    if checkpoint is None:
        found = sorted(config.CHECKPOINT_DIR.glob("ght_A1_C1_all_seed*.pt"))
        if not found:
            raise SystemExit(f"no C1 checkpoint under {config.CHECKPOINT_DIR}")
        checkpoint = found[0]

    table = panel.load()
    selected = pd.read_parquet(config.GHT_PROCESSED / "ght_selected_pwms.parquet")
    pwms = baselines.read_pwms(table.tf)
    chosen = {}
    for row in selected.itertuples():
        for pwm in pwms[row.tf]:
            if pwm.name == row.pwm:
                chosen[row.tf] = pwm
                break

    banks = learned_filters(checkpoint, args.which)
    matches = best_against(banks, chosen)
    best_per_tf = matches.loc[matches.groupby("tf").similarity.idxmax()].reset_index(drop=True)
    null = best_against(shuffled(banks), chosen).groupby("tf").similarity.max()

    config.GHT_PROCESSED.mkdir(parents=True, exist_ok=True)
    matches.to_parquet(config.GHT_PROCESSED / "ght_filter_matches.parquet", index=False)
    beaten = sum(
        1 for r in best_per_tf.itertuples() if r.similarity > float(null.get(r.tf, np.inf))
    )
    meta = {
        "null_median": float(null.median()),
        "null_min": float(null.min()),
        "null_max": float(null.max()),
        "n_above_null": beaten,
        "checkpoint": str(checkpoint),
        "n_filters": sum(b.shape[0] for b in banks.values()),
        "widths": ", ".join(str(w) for w in sorted(banks)),
        "n_pwms": len(chosen),
    }
    path = config.REPORT_DIR / "ght_filters.md"
    path.write_text(report(matches, best_per_tf, meta))
    print(
        f"median best similarity {best_per_tf.similarity.median():.3f} over {len(best_per_tf)} "
        f"TFs; permuted null {null.median():.3f}; {beaten}/{len(best_per_tf)} above null"
    )
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
