#!/usr/bin/env python
"""Regenerate the markdown reports for one parsed source.

    python scripts/make_reports.py --source BAR15A

Reads `data/interim/<source>/<source>.parquet` and writes into `reports/`. The reports are
committed, so they are regenerated rather than hand-edited.
"""

from __future__ import annotations

import argparse

import pandas as pd

from snp2prot import reports, schema
from snp2prot.config import REPORTS_DIR, interim_table


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", required=True)
    args = ap.parse_args()
    source = args.source

    table = interim_table(source)
    if not table.exists():
        raise SystemExit(f"not parsed yet: {table}\nrun scripts/build_dataset.py --source {source}")
    df = pd.read_parquet(table)

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    written = []

    path = REPORTS_DIR / f"binarization_summary_{source}.md"
    path.write_text(reports.binarization_summary(df, source))
    written.append(path)

    # Per-source, because four sources would otherwise overwrite one file. The unqualified
    # cluster_inventory.md is reserved for the merged table in Phase 5.
    path = REPORTS_DIR / f"cluster_inventory_{source}.md"
    path.write_text(reports.cluster_inventory(df, source))
    written.append(path)

    rep = schema.validate(df, source=source)
    lines = [
        f"# Schema validation — {source}",
        "",
        "Regenerated by `scripts/make_reports.py`. Do not hand-edit.",
        "",
        f"**{'PASS' if rep.ok else 'FAIL'}** — {len(df):,} rows.",
        "",
    ]
    if rep.errors:
        lines += ["## Errors", ""] + [f"- {e}" for e in rep.errors] + [""]
    if rep.warnings:
        lines += ["## Warnings", ""] + [f"- {w}" for w in rep.warnings] + [""]
    if not rep.errors and not rep.warnings:
        lines += ["No errors or warnings.", ""]
    lines += ["## Summary statistics", "", "| stat | value |", "|---|---|"]
    for k, v in rep.stats.items():
        if isinstance(v, dict):
            v = ", ".join(f"{kk}: {vv:,}" for kk, vv in v.items())
        elif isinstance(v, int):
            v = f"{v:,}"
        lines.append(f"| `{k}` | {v} |")
    lines.append("")
    path = REPORTS_DIR / f"validation_{source}.md"
    path.write_text("\n".join(lines))
    written.append(path)

    for p in written:
        print(f"wrote {p.relative_to(REPORTS_DIR.parent)}")


if __name__ == "__main__":
    main()
