#!/usr/bin/env python
"""Is the shared space wide enough to express this data at all?

    python scripts/measure_ceilings.py [--out reports/representation_ceiling.md]

`T35`, reduced on 2026-08-26 to the one measurement that licenses a conclusion. Seconds, and it
reads a single cached artifact — the 8-mer matrix.

**This script used to run three probes and present them as a decomposition** — *which link is at
fault when the two-tower model loses to nearest-neighbour lookup?* The ridge and RBF probes were
removed because that reading does not follow: every probe of this kind is a **lower** bound on
its model class, so it can rule a component out when the number is high and can conclude nothing
when the number is low. The ridge probe additionally minimised squared error while being scored
by AUPR, and was violated on 5 of the 8 rows it was printed on. `snp2prot.evaluation.ceilings`
carries the full account.

What replaced them: whether a stronger or non-linear protein tower helps is settled by training
one and reading the AUPR off the same folds (`TODO.md` `T36`), not by bounding it.
"""

from __future__ import annotations

import argparse
import time
from pathlib import Path

import pandas as pd

from snp2prot import experiment, tracking
from snp2prot.config import PROCESSED_DIR, REPORTS_DIR
from snp2prot.data.matrix import KmerMatrix
from snp2prot.evaluation import ceilings

DEFAULT_OUT = REPORTS_DIR / "representation_ceiling.md"
GRID = PROCESSED_DIR / "training_folds.parquet"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--rank", action="append", type=int, dest="ranks", help="repeatable")
    args = ap.parse_args()

    started = time.time()
    matrix = KmerMatrix.load()
    ranks = tuple(args.ranks) if args.ranks else (16, 64, 256, 512)
    print(f"rank ceiling over {matrix.shape[0]} x {matrix.shape[1]} ...", flush=True)
    scores = ceilings.rank_ceiling(matrix, ranks)
    for rank, score in scores.items():
        print(f"  rank {rank:>4}: {score:.4f}")

    write_report(args.out, scores, experiment.load())
    print(f"wrote {args.out} in {time.time() - started:.0f}s")


def _achieved() -> pd.Series | None:
    """Mean achieved AUPR per regime, for the comparison that carries the point.

    Per regime rather than the single best run: the rank floor is computed **in sample over all
    1,338 domains**, so setting it beside a held-out number is not like for like. The comparison
    is only decisive where the gap is large, which is the hard regimes — and those are where the
    question is live anyway.
    """
    if not GRID.exists():
        return None
    return pd.read_parquet(GRID).groupby("regime").aupr.mean()


def write_report(path: Path, scores: dict[int, float], cfg: dict) -> None:
    width = int(cfg["model"]["width"])
    achieved = _achieved()
    lines = [
        "# Is the shared space wide enough?",
        "",
        "Generated by `scripts/measure_ceilings.py` (`T35`). One measurement, because it is the",
        "one that supports a conclusion.",
        "",
        "The two-tower's score matrix is `(B x D) @ (D x K)`, so it is rank `D` at most whatever",
        "the towers do. This truncates the SVD of the E-score matrix itself and asks whether a",
        "rank-`D` matrix can order these 8-mers at all.",
        "",
        "| rank | macro AUPR |",
        "|---:|---:|",
    ]
    for rank, score in scores.items():
        marker = "  ← the configured `model.width`" if rank == width else ""
        lines.append(f"| {rank} | {score:.4f}{marker} |")

    at_width = scores.get(width)
    hard = ("S2", "P1")
    lines += [
        "",
        "## How to read it — and how not to",
        "",
        "**This is a lower bound, not a ceiling, despite the function's name.** The factors are",
        "fitted to the matrix being scored, so it says nothing about generalisation; and the",
        "truncated SVD is optimal in *Frobenius norm*, which is not the metric, so the true best",
        "rank-`D` matrix scores higher still. Both errors point the same way, which is what makes",
        "it usable:",
        "",
        "> A lower bound licenses a conclusion only when the number comes out **high**. It can",
        "> rule a component *out* — a solution this good exists, so this is not what stops us. It",
        "> can never rule one *in*.",
        "",
    ]
    if at_width is not None and achieved is not None:
        rendered = ", ".join(f"{r} {achieved[r]:.3f}" for r in achieved.index)
        lines += [
            f"At the configured width the floor is **{at_width:.4f}**. The grid's mean AUPR per",
            f"regime is {rendered}.",
            "",
            "**The floor is measured in sample over all 1,338 domains and the grid numbers are",
            "held out, so this is not a like-for-like comparison and is only decisive where the",
            "gap is wide.** On the easiest regimes it is not: `P3` runs within a few percent of",
            "the floor, and nothing can be concluded there. On the regimes where the question is",
            "actually live it is unambiguous — "
            + ", ".join(f"{r} at {achieved[r]:.3f}" for r in hard if r in achieved.index)
            + f" against a floor of {at_width:.4f}. Those failures are not the shared space",
            f"running out of room at `D = {width}`; a representable solution exists far above",
            "them. **Width is not the binding constraint on the hard regimes.**",
        ]
    elif at_width is not None:
        lines += [
            f"At the configured width the floor is **{at_width:.4f}**. Compare it against the",
            "grid's per-regime AUPR once `scripts/run_grid.py` has run.",
        ]

    lines += [
        "",
        "**Two probes were removed from this report on 2026-08-26.** A ridge regression and an",
        "RBF kernel ridge were presented as upper bounds on the protein tower — *the tower is",
        "already extracting what a linear map of this embedding can extract* — and neither was a",
        "bound. The ridge minimised squared error on E-scores while being scored by AUPR, and the",
        "two-tower model (whose protein side *is* a linear map, fitted with a ranking loss)",
        "exceeded it on 5 of the 8 rows it was printed beside, by up to 68%. Whether a stronger",
        "or non-linear tower helps is now settled by training one — `TODO.md` `T36`.",
        "",
        "```bash",
        "python scripts/measure_ceilings.py",
        "```",
        "",
        tracking.provenance_line(),
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
